//  ----------------------- STRATEGY CONSTANT ---------------------

// 账号
/**
 * jq_binance_hkd_master: jiaqichengzju@gmail.com，香港身份证认证
 * th_binance_cny_master: chengjiaqi_zju@qq.com，詹婷慧身份证认证（但是法定姓名是成佳淇），用Jesse的返佣链接注册
 * th_binance_cny_sub01: thbinancecnysub01@gmail.com, th_binance_cny_master的第一个子账户     
 * jq_binance_cny_master: 545756054@qq.com，大陆身份证认证，没有开启2FA
 */

ALIASES = ["R01", "R06", "R12", "R24", "STR", "SRE"];

SUBSCRIPTION_LIST = [
    // CTA 
    'BinanceU|1000SHIBUSDT|perp|trade',
    // 'BinanceU|1000XECUSDT|perp|trade',
    'BinanceU|ADAUSDT|perp|trade',
    'BinanceU|ALICEUSDT|perp|trade',
    'BinanceU|ALGOUSDT|perp|trade',
    'BinanceU|ALPHAUSDT|perp|trade',
    'BinanceU|ANKRUSDT|perp|trade',
    'BinanceU|ATOMUSDT|perp|trade',
    // 'BinanceU|AUDIOUSDT|perp|trade',
    'BinanceU|AVAXUSDT|perp|trade',
    'BinanceU|AXSUSDT|perp|trade',
    'BinanceU|BALUSDT|perp|trade',
    'BinanceU|BANDUSDT|perp|trade',
    'BinanceU|BNBUSDT|perp|trade',
    'BinanceU|BTCDOMUSDT|perp|trade',
    'BinanceU|BTCUSDT|perp|trade',
    'BinanceU|C98USDT|perp|trade',
    'BinanceU|CELOUSDT|perp|trade',
    'BinanceU|CELRUSDT|perp|trade',
    'BinanceU|CTKUSDT|perp|trade',
    'BinanceU|CTSIUSDT|perp|trade',
    // 'BinanceU|CRVUSDT|perp|trade',
    'BinanceU|DASHUSDT|perp|trade',
    'BinanceU|DOTUSDT|perp|trade',
    'BinanceU|DYDXUSDT|perp|trade',
    'BinanceU|EGLDUSDT|perp|trade',
    'BinanceU|ENJUSDT|perp|trade',
    'BinanceU|ETCUSDT|perp|trade',
    'BinanceU|ETHUSDT|perp|trade',
    'BinanceU|FILUSDT|perp|trade',
    'BinanceU|FTMUSDT|perp|trade',
    'BinanceU|FLOWUSDT|perp|trade',
    'BinanceU|GRTUSDT|perp|trade',
    'BinanceU|GTCUSDT|perp|trade',
    'BinanceU|HBARUSDT|perp|trade',
    'BinanceU|HOTUSDT|perp|trade',
    'BinanceU|IOTAUSDT|perp|trade',
    'BinanceU|KSMUSDT|perp|trade',
    'BinanceU|LINAUSDT|perp|trade',
    'BinanceU|LTCUSDT|perp|trade',
    'BinanceU|MANAUSDT|perp|trade',
    'BinanceU|MKRUSDT|perp|trade',
    'BinanceU|MTLUSDT|perp|trade',
    'BinanceU|NEARUSDT|perp|trade',
    'BinanceU|NKNUSDT|perp|trade',
    'BinanceU|OCEANUSDT|perp|trade',
    'BinanceU|ONTUSDT|perp|trade',
    'BinanceU|QTUMUSDT|perp|trade',
    'BinanceU|RSRUSDT|perp|trade',
    'BinanceU|RUNEUSDT|perp|trade',
    'BinanceU|SANDUSDT|perp|trade',
    'BinanceU|SKLUSDT|perp|trade',
    'BinanceU|SOLUSDT|perp|trade',
    'BinanceU|SXPUSDT|perp|trade',
    'BinanceU|THETAUSDT|perp|trade',
    'BinanceU|VETUSDT|perp|trade',
    'BinanceU|WAVESUSDT|perp|trade',
    'BinanceU|XEMUSDT|perp|trade',
    // 'BinanceU|XRPUSDT|perp|trade',
    'BinanceU|XTZUSDT|perp|trade',
    'BinanceU|YFIUSDT|perp|trade',
    'BinanceU|ZECUSDT|perp|trade',
    'BinanceU|ZILUSDT|perp|trade',

    // XES
    // 'BinanceU|XEMUSDT|perp|bestquote',
    // 'BinanceU|CELOUSDT|perp|bestquote',
    // 'BinanceU|FLOWUSDT|perp|bestquote',
    // 'BinanceU|CRVUSDT|perp|bestquote',

    // spread arbitrage
    // 'BinanceU|XEMUSDT|perp|bestquote',
    // 'OKX|CRVUSDT|perp|bestquote'
]

POS_STATUS = {
    EMPTY: "EMPTY",
    LONG: "LONG",
    EMPTY: "EMPTY",
    TBA: "TBA"
}

ORDER_LABEL = {
    UP: "UP",
    DN: "DN",
    ANTI_L: "ANTI_L",
    ANTI_S: "ANTI_S",
    REVERSE: "REVERSE"
}

LABELMAP = {
    "UP": "UP",
    "DN": "DN",
    "ANTI_L|STOPLOSS": "LS",
    "ANTI_L|REVERSE": "LR",
    "ANTI_S|STOPLOSS": "SS",
    "ANTI_S|REVERSE": "SR"
}



MAX_ORDER_SIZE_WHITELIST = [
    'Ftx.USDTUSD.perp',
    'Ftx.USDTUSD.quarter',
    'Ftx.USDTUSD.next_quarter',
    'Ftx.USDTUSD.spot',
    'Binance.BUSDUSDT.spot',
];



UI_UNIT_PRECISION = {
    BTC: 3,
    ETH: 2,

    BNB: 2,
    FTT: 1,
    OKB: 1,
    HT: 1,

    LTC: 1,
    ETC: 1,
    ADA: 0,
    DOT: 1,
    DOGE: 0,
    SOL: 2,
    XRP: 0,
    GMT: 0,
    NEAR: 1,
    TRX: 0,
    APE: 1,
    AVAX: 1,
    FTM: 0,
    GALA: 0,
    GAL: 0,
    WAVES: 1,
    LINK: 1,
    BCH: 2,
    EOS: 0,
    ATOM: 1,
    MANA: 0,
    SAND: 0,
    AXS: 1,
    EGLD: 1,
    UNI: 1,
    MATIC: 0,
    XMR: 2,

    CNY: 0,
    USD: 0,
    USDT: 0,
};

UI_PRICE_PRECISION = {
    BTC: 0,
    ETH: 1,

    BNB: 1,
    FTT: 2,
    OKB: 2,
    HT: 2,

    LTC: 2,
    ETC: 3,
    ADA: 4,
    DOT: 3,
    DOGE: 5,
    SOL: 2,
    XRP: 4,
    GMT: 4,
    NEAR: 4,
    TRX: 5,
    APE: 3,
    AVAX: 2,
    FTM: 4,
    GALA: 5,
    GAL: 3,
    WAVES: 3,
    LINK: 3,
    BCH: 2,
    EOS: 4,
    ATOM: 3,
    MANA: 4,
    SAND: 4,
    AXS: 2,
    EGLD: 3,
    UNI: 3,
    MATIC: 4,
    XMR: 2,

    USDT: 4,
};

//  ----------------------- Common ---------------------
LATENCY_ALARM_LIMIT = 300000;

LATENCY_LIMIT = {
    TRADE: 60000,
    ORDERBOOK: 5000,
    QUOTETICKER: 5000,
    POSITION: 300000,
    INDEX: 30000,
    SPREAD: 15000,
    MACD: 60000,
    ACCOUNT: 30000,
    KLINE: 120000,
    FUNDING: 5 * 60000
};

OB_LATENCY_EXCEPTIONS = {
    'Binance.ETHBTC.spot': 5000,
    'Binance.BNBBTC.spot': 5000,
    'Binance.BUSDUSDT.spot': 60000,
    'BinanceC.BNBUSD.perp': 5000,
    'BinanceC.BNBUSD.quarter': 10000,
    'BinanceC.BNBUSD.next_quarter': 15000,

    'BinanceU.BTCUSDT.quarter': 5000,
    'BinanceU.BTCUSDT.next_quarter': 8000,
    'BinanceU.ETHUSDT.quarter': 5000,
    'BinanceU.ETHUSDT.next_quarter': 8000,
    'BinanceC.ADAUSD.quarter': 10000,
    'BinanceC.ADAUSD.next_quarter': 15000,
    'BinanceC.LINKUSD.quarter': 10000,
    'BinanceC.LINKUSD.next_quarter': 15000,
    'BinanceC.XRPUSD.quarter': 10000,
    'BinanceC.XRPUSD.next_quarter': 15000,
    'BinanceC.DOTUSD.quarter': 10000,
    'BinanceC.DOTUSD.next_quarter': 15000,
    'BinanceC.LTCUSD.quarter': 10000,
    'BinanceC.LTCUSD.next_quarter': 15000,

    // 'BitMEX.BTCUSD.perp': 5000,
    'BitMEX.BTCUSD.quarter': 10000,
    'BitMEX.BTCUSD.next_quarter': 10000,
    // 'BitMEX.ETHUSD.perp': 5000,
    'BitMEX.ETHUSD.quarter': 15000,
    'BitMEX.ETHUSD.next_quarter': 20000,
    'BitMEX.ETHBTC.quarter': 30000,
    'BitMEX.ETHBTC.next_quarter': 30000,

    'Ftx.BTCUSD.quarter': 3000,
    'Ftx.BTCUSD.next_quarter': 5000,
    'Ftx.ETHUSD.quarter': 3000,
    'Ftx.ETHUSD.next_quarter': 5000,
    'Ftx.BNBUSD.quarter': 8000,
    'Ftx.BNBUSD.next_quarter': 8000,
    'Ftx.FTTUSD.perp': 5000,
    'Ftx.USDTUSD.perp': 30 * 60000,
    'Ftx.USDTUSD.quarter': 30 * 60000,
    'Ftx.USDTUSD.spot': 30 * 60000,
};

ABNORMAL_LATENCY = {
    AWS_JP: {
        Binance: 30,
        BinanceC: 35,
        BinanceU: 50,
        Huobi: 30,
        HuobiSu: 35,
        HuobiSwap: 35,
        HuobiFuture: 35,
        BitMEX: 150
    },
    AWS_IR: {
        Binance: 150,
        BinanceC: 150,
        BinanceU: 150,
        Huobi: 150,
        HuobiSu: 150,
        HuobiSwap: 150,
        HuobiFuture: 150,
        BitMEX: 35
    }
};


// for good liquidation and tight spread identifier
TIGHT_SPREAD_IDNTS = [
    'BinanceC.BTCUSD.perp',
    'BinanceC.BTCUSD.quarter',
    // 'BinanceC.BTCUSD.next_quarter',
    'BinanceC.ETHUSD.perp',
    'BinanceC.ETHUSD.quarter',
    // 'BinanceC.ETHUSD.next_quarter',
    'BinanceC.BNBUSD.perp',

    'Ftx.BTCUSD.perp',
    'Ftx.ETHUSD.perp',
    'Ftx.USDTUSD.perp',

    'BitMEX.BTCUSD.perp',
    'BitMEX.ETHUSD.perp',

    // 'HuobiSwap.BTCUSD.perp',
    // 'HuobiSwap.ETHUSD.perp',
    // 'HuobiSwap.XRPUSD.perp',
    // 'HuobiSwap.EOSUSD.perp',
    // 'HuobiSwap.NEOUSD.perp',
    // 'HuobiSwap.YFIIUSD.perp',

    'HuobiSU.BTCUSDT.perp',
    'HuobiSU.ETHUSDT.perp',
    // 'HuobiSU.XRPUSDT.perp',
    // 'HuobiSU.BNBUSDT.perp',

    'BinanceU.BTCUSDT.perp',
    'BinanceU.ETHUSDT.perp',
    // 'BinanceU.XRPUSDT.perp',
    // 'BinanceU.BNBUSDT.perp',

    // 'OKExC.BTCUSD.perp',
    // 'OKExC.ETHUSD.perp',

    // 'OKExU.BTCUSDT.perp',
    // 'OKExU.ETHUSDT.perp',

    // 'BybitC.BTCUSD.perp',
    // 'BybitC.ETHUSD.perp',

    // 'Deribit.BTCUSD.perp',
    // 'Deribit.ETHUSD.perp',

    // 'Binance.BTCUSDT.spot',
    // 'Binance.ETHUSDT.spot',
    // 'Binance.BNBUSDT.spot',
    // 'Binance.ETHBTC.spot',
    // 'Binance.BNBBTC.spot',
];

INDEX_MAP = {
    USDTUSD: 'Ftx.USDTUSD.index',
    BUSDUSD: 'Ftx.USDTUSD.index',  // todo: to be replaced
    BUSDUSDT: 'Ftx.USDTUSD.index',  // todo: to be replaced

    BTCUSD: 'HuobiSwap.BTCUSD.index',
    ETHUSD: 'HuobiSwap.ETHUSD.index',
    BNBUSD: 'BinanceC.BNBUSD.index',

    ADAUSD: 'BinanceC.ADAUSD.index',
    DOTUSD: 'BinanceC.DOTUSD.index',
    LTCUSD: 'BinanceC.LTCUSD.index',
    ETCUSD: 'BinanceC.ETCUSD.index',
    BCHUSD: 'BinanceC.BCHUSD.index',
    LINKUSD: 'BinanceC.LINKUSD.index',
    DOGEUSD: 'BinanceC.DOGEUSD.index',
    SOLUSD: 'BinanceC.SOLUSD.index',
    EOSUSD: 'BinanceC.EOSUSD.index',
    XRPUSD: 'BinanceC.XRPUSD.index',
    ATOMUSD: 'BinanceC.ATOMUSD.index',
    MANAUSD: 'BinanceC.MANAUSD.index',
    SANDUSD: 'BinanceC.SANDUSD.index',

    GMTUSD: 'BinanceC.GMTUSD.index',
    NEARUSD: 'BinanceC.NEARUSD.index',
    TRXUSD: 'BinanceU.TRXBUSD.index',
    FTTUSD: 'BinanceU.FTTBUSD.index',
    APEUSD: 'BinanceU.APEBUSD.index',
    AVAXUSD: 'BinanceU.AVAXBUSD.index',
    FTMUSD: 'BinanceU.FTMBUSD.index',

    AXSUSD: 'BinanceC.AXSUSD.index',
    EGLDUSD: 'BinanceC.EGLDUSD.index',
    UNIUSD: 'BinanceC.UNIUSD.index',
    MATICUSD: 'BinanceC.MATICUSD.index',
    XMRUSD: 'BinanceC.XMRUSD.index',
    GALAUSD: 'BinanceU.GALABUSD.index',
    GALUSD: 'BinanceU.GALBUSD.index',
    WAVESUSD: 'BinanceU.WAVESBUSD.index',
    // ----------------------

    BTCBUSD: 'HuobiSwap.BTCUSD.index',
    ETHBUSD: 'HuobiSwap.ETHUSD.index',
    BNBBUSD: 'BinanceC.BNBUSD.index',

    ADABUSD: 'BinanceU.ADABUSD.index',
    DOTBUSD: 'BinanceU.DOTBUSD.index',
    LTCBUSD: 'BinanceU.LTCBUSD.index',
    ETCBUSD: 'BinanceC.ETCUSD.index',
    BCHBUSD: 'BinanceC.BCHUSD.index',
    LINKBUSD: 'BinanceU.LINKBUSD.index',
    DOGEBUSD: 'BinanceU.DOGEBUSD.index',
    SOLBUSD: 'BinanceU.SOLBUSD.index',
    EOSBUSD: 'BinanceC.EOSUSD.index',
    XRPBUSD: 'BinanceU.XRPBUSD.index',
    ATOMBUSD: 'BinanceC.ATOMUSD.index',
    MANABUSD: 'BinanceC.MANAUSD.index',
    SANDBUSD: 'BinanceU.SANDBUSD.index',

    GMTBUSD: 'BinanceU.GMTBUSD.index',
    NEARBUSD: 'BinanceU.NEARBUSD.index',
    TRXBUSD: 'BinanceU.TRXBUSD.index',
    FTTBUSD: 'BinanceU.FTTBUSD.index',
    APEBUSD: 'BinanceU.APEBUSD.index',
    AVAXBUSD: 'BinanceU.AVAXBUSD.index',
    FTMBUSD: 'BinanceU.FTMBUSD.index',

    AXSBUSD: 'BinanceC.AXSUSD.index',
    EGLDBUSD: 'BinanceC.EGLDUSD.index',
    UNIBUSD: 'BinanceC.UNIUSD.index',
    MATICBUSD: 'BinanceU.MATICBUSD.index',
    XMRBUSD: 'BinanceC.XMRUSD.index',
    GALABUSD: 'BinanceU.GALABUSD.index',
    GALBUSD: 'BinanceU.GALBUSD.index',
    WAVESBUSD: 'BinanceU.WAVESBUSD.index',

    // ----------------------
    BTCUSDT: 'HuobiSU.BTCUSDT.index',
    ETHUSDT: 'HuobiSU.ETHUSDT.index',
    BNBUSDT: 'HuobiSU.BNBUSDT.index',

    ADAUSDT: 'BinanceU.ADAUSDT.index',
    DOTUSDT: 'BinanceU.DOTUSDT.index',
    LTCUSDT: 'BinanceU.LTCUSDT.index',
    ETCUSDT: 'BinanceU.ETCUSDT.index',
    BCHUSDT: 'BinanceU.BCHUSDT.index',
    LINKUSDT: 'BinanceU.LINKUSDT.index',
    DOGEUSDT: 'BinanceU.DOGEUSDT.index',
    SOLUSDT: 'BinanceU.SOLUSDT.index',
    EOSUSDT: 'BinanceU.EOSUSDT.index',
    XRPUSDT: 'BinanceU.XRPUSDT.index',
    ATOMUSDT: 'BinanceU.ATOMUSDT.index',
    MANAUSDT: 'BinanceU.MANAUSDT.index',
    SANDUSDT: 'BinanceU.SANDUSDT.index',

    GMTUSDT: 'BinanceU.GMTUSDT.index',
    NEARUSDT: 'BinanceU.NEARUSDT.index',
    TRXUSDT: 'BinanceU.TRXUSDT.index',
    FTTUSDT: 'BinanceU.FTTUSDT.index',
    APEUSDT: 'BinanceU.APEUSDT.index',
    AVAXUSDT: 'BinanceU.AVAXUSDT.index',
    FTMUSDT: 'BinanceU.FTMUSDT.index',

    AXSUSDT: 'BinanceU.AXSUSDT.index',
    EGLDUSDT: 'BinanceU.EGLDUSDT.index',
    UNIUSDT: 'BinanceU.UNIUSDT.index',
    MATICUSDT: 'BinanceU.MATICUSDT.index',
    XMRUSDT: 'BinanceU.XMRUSDT.index',
    GALAUSDT: 'BinanceU.GALAUSDT.index',
    GALUSDT: 'BinanceU.GALUSDT.index',
    WAVESUSDT: 'BinanceU.WAVESUSDT.index',
};

ALARM_REASON = {
    LEVERAGE: '00',
    BETA: '01',
    PNL: '02',
    INFRA: '03',
    BUG: '04',
    ACT: '05',
    FAILED: '06',
    MARKET: '07',
    CONFIG: '08',
    BAN: '09',
    EXCHANGE: '10',
    ABNORMAL: '11',
    RISK: '22'
};

ALARM_ACT_MAP = {
    ACT_MMM: '11',
    ACT_PMM: '11',
    ACT_JUN: '11',
    ACT_PMJ: '11',
    ACT_XUE: '11',
    ACT_SMM: '55',
    ACT_CTA: '77',
    ACT_TEST: '77'
};

QUOTE_SIDE = {
    ASK: 'ask',
    BID: 'bid'
};

FEE_TYPE = {
    MAKER: 'maker',
    TAKER: 'taker'
};

ACT = {
    DEFAULT: 'ACT_MMM',

    ACT_MMM: 'ACT_MMM',
    ACT_PMM: 'ACT_PMM',
    ACT_JUN: 'ACT_JUN',
    ACT_PMJ: 'ACT_PMJ',
    ACT_PMX: 'ACT_PMX',
    ACT_XUE: 'ACT_XUE',
    ACT_HFT: 'ACT_HFT',
    ACT_SMM: 'ACT_SMM',

    ACT_CTA: 'ACT_CTA',
    ACT_TEST: 'ACT_TEST',
    ACT_VOL: 'ACT_VOL',
    ACT_OPTION: 'ACT_OPTION',
    ACT_FUNDING: 'ACT_FUNDING',
    ACT_QUANTO: 'ACT_QUANTO',
    ACT_STATARB: 'ACT_STATARB',
};

UI_TABLE = {
    ACTSUM: 'ActSum',
    EXECUTION: 'Execution_Monitor',
    HEDGING: 'Hedging_Monitor',
    IMBALANCE: 'Imbalance_Monitor',
    POSITION: 'Position_Monitor',
    FUNDING: 'Funding_Monitor',
    BALANCE: 'Balance_Monitor',
    MARGIN: 'Margin_Monitor',
    MARKETMAKING: 'MarketMaking_Monitor',
    SUBBALANCE: 'SubBalance_Monitor',
    SUBMARGIN: 'SubMargin_Monitor',
};

EX_ABBR = {
    BitMEX: 'BMX',
    Huobi: 'HB',
    HuobiSU: 'HSU',
    HuobiSC: 'HSC',
    HuobiFC: 'HFC',
    HuobiFU: 'HFU',

    // TODO
    HuobiSwap: 'HBS',
    HuobiFuture: 'HBF',

    Binance: 'BN',
    BinanceC: 'BNC',
    BinanceU: 'BNU',
    OKEx: 'OK',
    OKExU: 'OKU',
    OKExC: 'OKC',
    Bybit: 'BY',
    BybitC: 'BYC',
    BybitU: 'BYU',
    Ftx: 'FTX',
    Deribit: 'DRB',
    Bithumb: 'BTH',
    KrakenC: 'KKC'
};

CONT_ABBR = {
    spot: 'SP',
    perp: 'PP',
    this_week: 'CW',
    next_week: 'NW',
    this_month: 'CM',
    next_month: 'NM',
    quarter: 'CQ',
    next_quarter: 'NQ',
    next_two_quarter: 'TQ',
};

STRATEGY_KEY_ABBR = {
    // Header
    'Huobi-HuobiSU.BTCUSDT.perp': 'HBX|XX|BTC|PP|HSU',
    'Huobi-HuobiSU.ETHUSDT.perp': 'HBX|XX|ETH|PP|HSU',

    'Binance-HuobiSU.BTCUSDT.perp': 'BNX|XX|BTC|PP|HSU',
    'Binance-HuobiSU.ETHUSDT.perp': 'BNX|XX|ETH|PP|HSU',

    'Binance-BinanceC.BTCUSD.perp': 'BNX|XX|BTC|PP|BNC',
    'Binance-BinanceC.ETHUSD.perp': 'BNX|XX|ETH|PP|BNC',
    'Binance-BinanceC.BNBUSD.perp': 'BNX|XX|BNB|PP|BNC',

    'Binance-BinanceU.BTCUSDT.perp': 'BNX|XX|BTC|PP|BNU',
    'Binance-BinanceU.ETHUSDT.perp': 'BNX|XX|ETH|PP|BNU',
    'Binance-BinanceU.BNBUSDT.perp': 'BNX|XX|BNB|PP|BNU',
    'Binance-BinanceU.FTTUSDT.perp': 'BNX|XX|FTT|PP|BNU',

    'Binance-BinanceU.BTCUSDT.quarter': 'BNX|XX|BTC|CQ|BNU',
    'Binance-BinanceU.ETHUSDT.quarter': 'BNX|XX|ETH|CQ|BNU',
    'Binance-BinanceU.BNBUSDT.quarter': 'BNX|XX|BNB|CQ|BNU',

    'Binance-BinanceU.BTCUSDT.next_quarter': 'BNX|XX|BTC|NQ|BNU',
    'Binance-BinanceU.ETHUSDT.next_quarter': 'BNX|XX|ETH|NQ|BNU',
    'Binance-BinanceU.BNBUSDT.next_quarter': 'BNX|XX|BNB|NQ|BNU',

    'BitMEX-BitMEX.BTCUSD.perp': 'BMX|XX|BTC|PP|BMX',
    'BitMEX-BitMEX.ETHUSD.perp': 'BMX|XX|ETH|PP|BMX',

    'Ftx-Ftx.BTCUSD.perp': 'FTX|XX|BTC|PP|FTX',
    'Ftx-Ftx.ETHUSD.perp': 'FTX|XX|ETH|PP|FTX',
    'Ftx-Ftx.BNBUSD.perp': 'FTX|XX|BNB|PP|FTX',
    'Ftx-Ftx.FTTUSD.perp': 'FTX|XX|FTT|PP|FTX',

    // BinanceC Market Making
    'BinanceC-BinanceC.BTCUSD.perp':         'BNC|XX|BTC|PP|BNC',
    'BinanceC-BinanceC.BTCUSD.quarter':      'BNC|XX|BTC|CQ|BNC',
    'BinanceC-BinanceC.BTCUSD.next_quarter': 'BNC|XX|BTC|NQ|BNC',
    'BinanceC-BinanceC.ETHUSD.perp':         'BNC|XX|ETH|PP|BNC',
    'BinanceC-BinanceC.ETHUSD.quarter':      'BNC|XX|ETH|CQ|BNC',
    'BinanceC-BinanceC.ETHUSD.next_quarter': 'BNC|XX|ETH|NQ|BNC',
    'BinanceC-BinanceC.BNBUSD.perp':         'BNC|XX|BNB|PP|BNC',
    'BinanceC-BinanceC.BNBUSD.quarter':      'BNC|XX|BNB|CQ|BNC',
    'BinanceC-BinanceC.BNBUSD.next_quarter': 'BNC|XX|BNB|NQ|BNC',
    'BinanceC-BinanceC.ADAUSD.perp':         'BNC|XX|ADA|PP|BNC',
    'BinanceC-BinanceC.ADAUSD.quarter':      'BNC|XX|ADA|CQ|BNC',
    'BinanceC-BinanceC.ADAUSD.next_quarter': 'BNC|XX|ADA|NQ|BNC',
    'BinanceC-BinanceC.DOTUSD.perp':         'BNC|XX|DOT|PP|BNC',
    'BinanceC-BinanceC.DOTUSD.quarter':      'BNC|XX|DOT|CQ|BNC',
    'BinanceC-BinanceC.DOTUSD.next_quarter': 'BNC|XX|DOT|NQ|BNC',
    'BinanceC-BinanceC.LTCUSD.perp':         'BNC|XX|LTC|PP|BNC',
    'BinanceC-BinanceC.LTCUSD.quarter':      'BNC|XX|LTC|CQ|BNC',
    'BinanceC-BinanceC.LTCUSD.next_quarter': 'BNC|XX|LTC|NQ|BNC',
    'BinanceC-BinanceC.XRPUSD.perp':         'BNC|XX|XRP|PP|BNC',
    'BinanceC-BinanceC.XRPUSD.quarter':      'BNC|XX|XRP|CQ|BNC',
    'BinanceC-BinanceC.XRPUSD.next_quarter': 'BNC|XX|XRP|NQ|BNC',
    'BinanceC-BinanceC.BCHUSD.perp':         'BNC|XX|BCH|PP|BNC',
    'BinanceC-BinanceC.BCHUSD.quarter':      'BNC|XX|BCH|CQ|BNC',
    'BinanceC-BinanceC.BCHUSD.next_quarter': 'BNC|XX|BCH|NQ|BNC',
    'BinanceC-BinanceC.LINKUSD.perp':         'BNC|XX|LINK|PP|BNC',
    'BinanceC-BinanceC.LINKUSD.quarter':      'BNC|XX|LINK|CQ|BNC',
    'BinanceC-BinanceC.LINKUSD.next_quarter': 'BNC|XX|LINK|NQ|BNC',

    'BinanceC-BinanceU.BTCUSDT.perp':        'BNC|XX|BTC|PP|BNU',
    'BinanceC-BinanceU.BTCBUSD.perp':        'BNC|XX|BTCB|PP|BNU',
    'BinanceC-BinanceU.ETHUSDT.perp':        'BNC|XX|ETH|PP|BNU',
    'BinanceC-BinanceU.ETHBUSD.perp':        'BNC|XX|ETHB|PP|BNU',
    'BinanceC-BinanceU.BNBUSDT.perp':        'BNC|XX|BNB|PP|BNU',
    'BinanceC-BinanceU.BNBBUSD.perp':        'BNC|XX|BNBB|PP|BNU',
    'BinanceC-BinanceU.ADAUSDT.perp':        'BNC|XX|ADA|PP|BNU',
    'BinanceC-BinanceU.ADABUSD.perp':        'BNC|XX|ADAB|PP|BNU',
    'BinanceC-BinanceU.LINKUSDT.perp':       'BNC|XX|LINK|PP|BNU',
    'BinanceC-BinanceU.XRPUSDT.perp':        'BNC|XX|XRP|PP|BNU',
    'BinanceC-BinanceU.DOTUSDT.perp':        'BNC|XX|DOT|PP|BNU',
    'BinanceC-BinanceU.LTCUSDT.perp':        'BNC|XX|LTC|PP|BNU',

    // -----------------------------Cross-----------------------------
    'BinanceC.ETHUSD.quarter|BinanceC.ETHUSD.perp|BinanceC.BTCUSD.quarter|BinanceC.BTCUSD.perp':           'BNC|CQ|ETHBTC|CQ|BNC',
    'BinanceC.ETHUSD.next_quarter|BinanceC.ETHUSD.perp|BinanceC.BTCUSD.next_quarter|BinanceC.BTCUSD.perp': 'BNC|NQ|ETHBTC|NQ|BNC',

    'BinanceU.ETHUSDT.quarter|BinanceU.ETHUSDT.perp|BinanceU.BTCUSDT.quarter|BinanceU.BTCUSDT.perp':       'BNU|CQ|ETHBTC|CQ|BNU',
    'Ftx.ETHUSD.quarter|Ftx.ETHUSD.perp|Ftx.BTCUSD.quarter|Ftx.BTCUSD.perp':           'FTX|CQ|ETHBTC|CQ|FTX',
    'Ftx.ETHUSD.next_quarter|Ftx.ETHUSD.perp|Ftx.BTCUSD.next_quarter|Ftx.BTCUSD.perp': 'FTX|NQ|ETHBTC|NQ|FTX',

    'Ftx.ETHUSD.quarter|Ftx.ETHUSD.perp|BinanceU.BTCUSDT.quarter|BinanceU.BTCUSDT.perp': 'FTX|CQ|ETHBTC|CQ|BNU',
    'Ftx.BTCUSD.quarter|Ftx.BTCUSD.perp|BinanceU.BTCUSDT.quarter|BinanceU.BTCUSDT.perp': 'FTX|CQ|BTCBTC|CQ|BNU',
    'Ftx.ETHUSD.quarter|Ftx.ETHUSD.perp|BinanceU.ETHUSDT.quarter|BinanceU.ETHUSDT.perp': 'FTX|CQ|ETHETH|CQ|BNU',
    'Ftx.BTCUSD.quarter|Ftx.BTCUSD.perp|BinanceU.ETHUSDT.quarter|BinanceU.ETHUSDT.perp': 'FTX|CQ|BTCETH|CQ|BNU',

    // 'Ftx.ETHUSD.perp|BinanceU.ETHUSDT.perp|Ftx.BTCUSD.perp|BinanceU.BTCUSDT.perp':       'FTX|PP|ETHBTC|PP|BNU',

    'BinanceU.BTCBUSD.perp|Ftx.USDTUSD.perp|BinanceU.BTCUSDT.perp': 'BNU|PP|BBTCBTC|PP|BNU',
    'BinanceU.ETHBUSD.perp|Ftx.USDTUSD.perp|BinanceU.ETHUSDT.perp': 'BNU|PP|BETHETH|PP|BNU',
    'BinanceU.BNBBUSD.perp|Ftx.USDTUSD.perp|BinanceU.BNBUSDT.perp': 'BNU|PP|BBNBBNB|PP|BNU',
};

STRATEGY = {
    Demo: 'Demo',
    JACKIE: 'JACKIE',
    StatisticalArbitrage: 'StatisticalArbitrage',
    StatarbMarketMaking: 'StatisticalArbitrageMarketMaking',
    AutoBalance: 'AutoBalance',
    AccountMonitor: 'AccountMonitor',
    FundingMonitor: 'FundingMonitor',
    QuantoCorvolTrading: 'QuantoCorvolTrading',
    QuantoCorvolHedging: 'QuantoCorvolHedging',

    QuantoSpreadArbitrage: 'QuantoSpreadArbitrage',
    QuantoAutoBalance: 'QuantoAutoBalance',
    IndicatorManager: 'IndicatorManager',
    SpreadScript: 'SpreadScript',
    TriangleScript: 'TriangleScript',
    TriangleExecution: 'TriangleExecution',
    AlgorithmicExecution: 'AlgorithmicExecution',

    QuantoVolTrading: 'QuantoVolTrading',
    QuantoDynamicHedging: 'QuantoDynamicHedging',
    QuantoVolatilityTrading: 'QuantoVolatilityTrading',
    FundingStatArbitrage: 'FundingStatArbitrage',
    FundingTriArbitrage: 'FundingTriArbitrage',
    OptionGammaTrading: 'OptionGammaTrading',
    OptionMarketMaking: 'OptionMarketMaking',
    OptionDeltaHedging: 'OptionDeltaHedging',
    FlashExecution: 'FlashExecution',
    StrategyManager: 'StrategyManager',
};

INDICATOR = {
    FUNDING: 'funding',
    // KLINE: 'kline',
    SPREAD: 'spread',
    MACD: 'macd',
    BB: 'bollinger',
    HV: 'histvol',
    CC: 'corr'
};

FUNDING_TYPE = {
    LAST: 'last_rate',
    CURRENT: 'rate',
    NEXT: 'next_rate'
};

OK = 'OK';

FAIL_REASON = {
    // send/cancel/inspect/query order
    OVERLOAD: 'overload',
    EXCEED_LIMIT: 'exceed_limit',
    TIMEOUT: 'timeout',
    BAD_PARA: 'bad_parameter',
    // NOT_OPEN: 'not_open',    // after settlement
    NETWORK: 'network',
    DUP_CID: 'duplicate_id',
    FAK: 'fak',
    SETTLE: 'settlement',
    // send order
    POST_ONLY: 'post_only',
    REJECTED: 'rejected',
    // STOP_PRICE: 'stop_price',
    MARGIN: 'margin',
    BALANCE: 'balance',
    // cancel and modify order
    CANCELLED: 'cancelled',
    CANCELLING: 'cancelling',
    NOT_EXIST: 'not_exist',
    UNKNOWN: 'unknown',
    FILLED: 'filled',
    BAN: 'ban'
};

MANUAL_QT = ['000', '111', '222', '333', '444', '555', '666', '777', '888', '999'];

MODIFY_ORDER_EX = [
    // 'BinanceC',
    'BitMEX'
];

STABLE_COIN = [
    'USDT',
    'USDC',
    'PAX',
    'BUSD',
    'USDK',
    'HUSD',
    'TUSD',
];

EX_COIN = {
    OKB: 'OKEx',
    BNB: 'Binance',
    HT: 'Huobi',
    FTT: 'FTX',
    BMEX: 'BitMEX'
};

POSITION_WS_UPDATE_EXCHANGES = [
    'Binance',
    'BinanceC',
    'BinanceU',
    'Huobi',
    'HuobiSU',
    'HuobiSwap',
    'HuobiFuture',
    'OKEx',
    'OKExC',
    'OKExU',
    'BitMEX'
];

QUANTO = {
    'BitMEX.ETHUSD.perp': 1e-6,
    'BitMEX.ETHUSD.quarter': 1e-6,
    'BitMEX.ETHUSD.next_quarter': 1e-6,
    'BitMEX.ADAUSD.perp': 1e-4,
    'BitMEX.AVAXUSD.perp': 1e-5,
    'BitMEX.AXSUSD.perp': 1e-6,
    'BitMEX.BCHUSD.perp': 1e-6,
    'BitMEX.BNBUSD.perp': 1e-6,
    'BitMEX.DOGEUSD.perp': 1e-6,
    'BitMEX.DOTUSD.perp': 1e-5,
    'BitMEX.EOSUSD.perp': 1e-4,
    'BitMEX.LINKUSD.perp': 1e-5,
    'BitMEX.LTCUSD.perp': 2e-6,
    'BitMEX.LUNAUSD.perp': 1e-5,
    'BitMEX.SOLUSD.perp': 1e-6,
    'BitMEX.XRPUSD.perp': 2e-4,
};

SLIPPAGE = {
    'BinanceU.BTCUSDT.perp': 0,
    'BinanceU.BTCUSDT.quarter': 0.0001,
    'BinanceU.BTCUSDT.next_quarter': 0.0001,
    'BinanceU.ETHUSDT.perp': 0,
    'BinanceU.ETHUSDT.quarter': 0.00015,
    'BinanceU.ETHUSDT.next_quarter': 0.00015,
    'BinanceU.XRPUSDT.perp': 0.0001,
    'BinanceU.BNBUSDT.perp': 0.0001,
    'BinanceU.FTTUSDT.perp': 0.0001,

    'BinanceC.BTCUSD.perp': 0,
    'BinanceC.ETHUSD.perp': 0,
    'BinanceC.BNBUSD.perp': 0.00002,
    'BinanceC.BTCUSD.quarter': 0.00001,
    'BinanceC.ETHUSD.quarter': 0.00001,
    'BinanceC.BNBUSD.quarter': 0.00003,
    'BinanceC.BTCUSD.next_quarter': 0.00003,
    'BinanceC.ETHUSD.next_quarter': 0.00003,
    'BinanceC.BNBUSD.next_quarter': 0.00005,
    'BinanceC.ADAUSD.perp': 0,
    'BinanceC.ADAUSD.quarter': 0.00003,
    'BinanceC.ADAUSD.next_quarter': 0.00005,
    'BinanceC.DOTUSD.perp': 0,
    'BinanceC.DOTUSD.quarter': 0.0001,
    'BinanceC.DOTUSD.next_quarter': 0.00015,
    'BinanceC.LTCUSD.perp': 0,
    'BinanceC.LTCUSD.quarter': 0.00003,
    'BinanceC.LTCUSD.next_quarter': 0.00005,
    'BinanceC.XRPUSD.perp': 0,
    'BinanceC.XRPUSD.quarter': 0.00003,
    'BinanceC.XRPUSD.next_quarter': 0.00005,
    'BinanceC.BCHUSD.perp': 0,
    'BinanceC.BCHUSD.quarter': 0.00005,
    'BinanceC.BCHUSD.next_quarter': 0.00008,
    'BinanceC.LINKUSD.perp': 0,
    'BinanceC.LINKUSD.quarter': 0.00003,
    'BinanceC.LINKUSD.next_quarter': 0.00005,

    'HuobiFuture.BTCUSD.this_week': 0.0001,
    'HuobiFuture.BTCUSD.next_week': 0.00015,
    'HuobiFuture.BTCUSD.quarter': 0.00005,
    'HuobiFuture.BTCUSD.next_quarter': 0.0001,
    'HuobiFuture.ETHUSD.this_week': 0.0001,
    'HuobiFuture.ETHUSD.next_week': 0.00015,
    'HuobiFuture.ETHUSD.quarter': 0.00005,
    'HuobiFuture.ETHUSD.next_quarter': 0.0001,

    'Binance.BTCUSDT.spot': 0.00001,
    'Binance.ETHUSDT.spot': 0.00002,
    'Binance.BNBUSDT.spot': 0.00003,
    'Binance.BTCBUSD.spot': 0.00001,
    'Binance.ETHBUSD.spot': 0.00002,
    'Binance.BNBBUSD.spot': 0.00003,
    'Binance.ETHBTC.spot': 0.00003,
    'Binance.BNBBTC.spot': 0.00003,
    'Binance.BUSDUSDT.spot': 0,

    'Ftx.BTCUSD.perp': 0,
    'Ftx.BTCUSD.quarter': 0.00002,
    'Ftx.BTCUSD.next_quarter': 0.00004,
    'Ftx.ETHUSD.perp': 0,
    'Ftx.ETHUSD.quarter': 0.00003,
    'Ftx.ETHUSD.next_quarter': 0.00005,
    'Ftx.BNBUSD.perp': 0.00002,
    'Ftx.BNBUSD.quarter': 0.00004,
    'Ftx.FTTUSD.perp': 0.00002,
    'Ftx.USDTUSD.perp': 0,
    'Ftx.USDTUSD.quarter': 0,
    'Ftx.USDTUSD.spot': 0,

    'Huobi.ETHBTC.spot': 0.0001,
    'Huobi.ETHUSDT.spot': 0.00008,
    'Huobi.BTCUSDT.spot': 0.00005,

    'HuobiSwap.BTCUSD.perp': 0,
    'HuobiSwap.ETHUSD.perp': 0,

    'HuobiSU.BTCUSDT.perp': 0,
    'HuobiSU.ETHUSDT.perp': 0,
    'HuobiSU.BNBUSDT.perp': 0.00015,

    // TODO: refine bitmex slippage
    'BitMEX.BTCUSD.perp': 0,
    'BitMEX.BTCUSD.quarter': 0,
    'BitMEX.BTCUSD.next_quarter': 0,
    'BitMEX.ETHUSD.perp': 0,
    'BitMEX.ETHUSD.quarter': 0,
    'BitMEX.ETHUSD.next_quarter': 0,
    'BitMEX.ETHBTC.quarter': 0,
    'BitMEX.ETHBTC.next_quarter': 0,

    'BitMEX.ADAUSD.perp': 0,
    'BitMEX.AVAXUSD.perp': 0,
    'BitMEX.AXSUSD.perp': 0,
    'BitMEX.BCHUSD.perp': 0,
    'BitMEX.BNBUSD.perp': 0,
    'BitMEX.DOGEUSD.perp': 0,
    'BitMEX.DOTUSD.perp': 0,
    'BitMEX.EOSUSD.perp': 0,
    'BitMEX.LINKUSD.perp': 0,
    'BitMEX.LTCUSD.perp': 0,
    'BitMEX.LUNAUSD.perp': 0,
    'BitMEX.SOLUSD.perp': 0,
    'BitMEX.XRPUSD.perp': 0,
};

CONTRACT_MULTIPLIER = {
    'BinanceU.BTCUSDT.perp': 1,
    'BinanceU.BTCUSDT.quarter': 1,
    'BinanceU.BTCUSDT.next_quarter': 1,
    'BinanceU.ETHUSDT.perp': 1,
    'BinanceU.ETHUSDT.quarter': 1,
    'BinanceU.ETHUSDT.next_quarter': 1,
    'BinanceU.BNBUSDT.perp': 1,
    'BinanceU.FTTUSDT.perp': 1,
    "BinanceU.BCHUSDT.perp": 1,
    "BinanceU.XRPUSDT.perp": 1,
    "BinanceU.EOSUSDT.perp": 1,
    "BinanceU.LTCUSDT.perp": 1,
    "BinanceU.LTCBUSD.perp": 1,
    "BinanceU.TRXUSDT.perp": 1,
    "BinanceU.ETCUSDT.perp": 1,
    "BinanceU.LINKUSDT.perp": 1,
    "BinanceU.LINKBUSD.perp": 1,
    "BinanceU.XLMUSDT.perp": 1,
    "BinanceU.ADAUSDT.perp": 1,
    "BinanceU.XMRUSDT.perp": 1,
    "BinanceU.DASHUSDT.perp": 1,
    "BinanceU.ZECUSDT.perp": 1,
    "BinanceU.XTZUSDT.perp": 1,
    "BinanceU.ATOMUSDT.perp": 1,
    "BinanceU.ONTUSDT.perp": 1,
    "BinanceU.IOTAUSDT.perp": 1,
    "BinanceU.BATUSDT.perp": 1,
    "BinanceU.VETUSDT.perp": 1,
    "BinanceU.NEOUSDT.perp": 1,
    "BinanceU.QTUMUSDT.perp": 1,
    "BinanceU.IOSTUSDT.perp": 1,
    "BinanceU.THETAUSDT.perp": 1,
    "BinanceU.ALGOUSDT.perp": 1,
    "BinanceU.ZILUSDT.perp": 1,
    "BinanceU.KNCUSDT.perp": 1,
    "BinanceU.ZRXUSDT.perp": 1,
    "BinanceU.COMPUSDT.perp": 1,
    "BinanceU.OMGUSDT.perp": 1,
    "BinanceU.DOGEUSDT.perp": 1,
    "BinanceU.SXPUSDT.perp": 1,
    "BinanceU.KAVAUSDT.perp": 1,
    "BinanceU.BANDUSDT.perp": 1,
    "BinanceU.RLCUSDT.perp": 1,
    "BinanceU.WAVESUSDT.perp": 1,
    "BinanceU.WAVESBUSD.perp": 1,
    "BinanceU.MKRUSDT.perp": 1,
    "BinanceU.SNXUSDT.perp": 1,
    "BinanceU.DOTUSDT.perp": 1,
    "BinanceU.DEFIUSDT.perp": 1,
    "BinanceU.YFIUSDT.perp": 1,
    "BinanceU.BALUSDT.perp": 1,
    "BinanceU.CRVUSDT.perp": 1,
    "BinanceU.TRBUSDT.perp": 1,
    "BinanceU.RUNEUSDT.perp": 1,
    "BinanceU.SUSHIUSDT.perp": 1,
    "BinanceU.SRMUSDT.perp": 1,
    "BinanceU.EGLDUSDT.perp": 1,
    "BinanceU.SOLUSDT.perp": 1,
    "BinanceU.ICXUSDT.perp": 1,
    "BinanceU.STORJUSDT.perp": 1,
    "BinanceU.BLZUSDT.perp": 1,
    "BinanceU.UNIUSDT.perp": 1,
    "BinanceU.AVAXUSDT.perp": 1,
    "BinanceU.FTMUSDT.perp": 1,
    "BinanceU.HNTUSDT.perp": 1,
    "BinanceU.ENJUSDT.perp": 1,
    "BinanceU.FLMUSDT.perp": 1,
    "BinanceU.TOMOUSDT.perp": 1,
    "BinanceU.RENUSDT.perp": 1,
    "BinanceU.KSMUSDT.perp": 1,
    "BinanceU.NEARUSDT.perp": 1,
    "BinanceU.AAVEUSDT.perp": 1,
    "BinanceU.FILUSDT.perp": 1,
    "BinanceU.RSRUSDT.perp": 1,
    "BinanceU.LRCUSDT.perp": 1,
    "BinanceU.MATICUSDT.perp": 1,
    "BinanceU.MATICBUSD.perp": 1,
    "BinanceU.OCEANUSDT.perp": 1,
    "BinanceU.CVCUSDT.perp": 1,
    "BinanceU.BELUSDT.perp": 1,
    "BinanceU.CTKUSDT.perp": 1,
    "BinanceU.AXSUSDT.perp": 1,
    "BinanceU.ALPHAUSDT.perp": 1,
    "BinanceU.ZENUSDT.perp": 1,
    "BinanceU.SKLUSDT.perp": 1,
    "BinanceU.GRTUSDT.perp": 1,
    "BinanceU.1INCHUSDT.perp": 1,
    "BinanceU.BTCBUSD.perp": 1,
    "BinanceU.CHZUSDT.perp": 1,
    "BinanceU.SANDUSDT.perp": 1,
    "BinanceU.SANDBUSD.perp": 1,
    "BinanceU.ANKRUSDT.perp": 1,
    "BinanceU.BTSUSDT.perp": 1,
    "BinanceU.LITUSDT.perp": 1,
    "BinanceU.UNFIUSDT.perp": 1,
    "BinanceU.REEFUSDT.perp": 1,
    "BinanceU.RVNUSDT.perp": 1,
    "BinanceU.SFPUSDT.perp": 1,
    "BinanceU.XEMUSDT.perp": 1,
    "BinanceU.BTCSTUSDT.perp": 1,
    "BinanceU.COTIUSDT.perp": 1,
    "BinanceU.CHRUSDT.perp": 1,
    "BinanceU.MANAUSDT.perp": 1,
    "BinanceU.ALICEUSDT.perp": 1,
    "BinanceU.HBARUSDT.perp": 1,
    "BinanceU.ONEUSDT.perp": 1,
    "BinanceU.LINAUSDT.perp": 1,
    "BinanceU.STMXUSDT.perp": 1,
    "BinanceU.DENTUSDT.perp": 1,
    "BinanceU.CELRUSDT.perp": 1,
    "BinanceU.HOTUSDT.perp": 1,
    "BinanceU.MTLUSDT.perp": 1,
    "BinanceU.OGNUSDT.perp": 1,
    "BinanceU.NKNUSDT.perp": 1,
    "BinanceU.SCUSDT.perp": 1,
    "BinanceU.DGBUSDT.perp": 1,
    "BinanceU.1000SHIBUSDT.perp": 1,
    "BinanceU.ICPUSDT.perp": 1,
    "BinanceU.BAKEUSDT.perp": 1,
    "BinanceU.GTCUSDT.perp": 1,
    "BinanceU.ETHBUSD.perp": 1,
    "BinanceU.BTCDOMUSDT.perp": 1,
    "BinanceU.TLMUSDT.perp": 1,
    "BinanceU.BNBBUSD.perp": 1,
    "BinanceU.ADABUSD.perp": 1,
    "BinanceU.XRPBUSD.perp": 1,
    "BinanceU.IOTXUSDT.perp": 1,
    "BinanceU.DOGEBUSD.perp": 1,
    "BinanceU.AUDIOUSDT.perp": 1,
    "BinanceU.RAYUSDT.perp": 1,
    "BinanceU.C98USDT.perp": 1,
    "BinanceU.MASKUSDT.perp": 1,
    "BinanceU.ATAUSDT.perp": 1,
    "BinanceU.SOLBUSD.perp": 1,
    "BinanceU.FTTBUSD.perp": 1,
    "BinanceU.DYDXUSDT.perp": 1,
    "BinanceU.1000XECUSDT.perp": 1,
    "BinanceU.GALAUSDT.perp": 1,
    "BinanceU.CELOUSDT.perp": 1,
    "BinanceU.ARUSDT.perp": 1,
    "BinanceU.KLAYUSDT.perp": 1,
    "BinanceU.ARPAUSDT.perp": 1,
    "BinanceU.CTSIUSDT.perp": 1,
    "BinanceU.LPTUSDT.perp": 1,
    "BinanceU.ENSUSDT.perp": 1,
    "BinanceU.PEOPLEUSDT.perp": 1,
    "BinanceU.ANTUSDT.perp": 1,
    "BinanceU.ROSEUSDT.perp": 1,
    "BinanceU.DUSKUSDT.perp": 1,
    "BinanceU.FLOWUSDT.perp": 1,
    "BinanceU.IMXUSDT.perp": 1,
    "BinanceU.API3USDT.perp": 1,
    "BinanceU.GMTUSDT.perp": 1,
    "BinanceU.APEUSDT.perp": 1,
    "BinanceU.BNXUSDT.perp": 1,
    "BinanceU.WOOUSDT.perp": 1,
    "BinanceU.JASMYUSDT.perp": 1,
    "BinanceU.DARUSDT.perp": 1,
    "BinanceU.GALUSDT.perp": 1,
    "BinanceU.AVAXBUSD.perp": 1,
    "BinanceU.NEARBUSD.perp": 1,
    "BinanceU.GMTBUSD.perp": 1,
    "BinanceU.APEBUSD.perp": 1,
    "BinanceU.GALBUSD.perp": 1,
    "BinanceU.FTMBUSD.perp": 1,
    "BinanceU.DODOBUSD.perp": 1,
    "BinanceU.ANCBUSD.perp": 1,
    "BinanceU.GALABUSD.perp": 1,
    "BinanceU.TRXBUSD.perp": 1,
    "BinanceU.1000LUNCBUSD.perp": 1,
    "BinanceU.DOTBUSD.perp": 1,

    "BinanceC.BTCUSD.perp": 100,
    "BinanceC.BTCUSD.quarter": 100,
    "BinanceC.BTCUSD.next_quarter": 100,
    "BinanceC.ETHUSD.perp": 10,
    "BinanceC.ETHUSD.quarter": 10,
    "BinanceC.ETHUSD.next_quarter": 10,
    "BinanceC.LINKUSD.perp": 10,
    "BinanceC.BNBUSD.perp": 10,
    "BinanceC.TRXUSD.perp": 10,
    "BinanceC.DOTUSD.perp": 10,
    "BinanceC.ADAUSD.perp": 10,
    "BinanceC.EOSUSD.perp": 10,
    "BinanceC.LTCUSD.perp": 10,
    "BinanceC.BCHUSD.perp": 10,
    "BinanceC.XRPUSD.perp": 10,
    "BinanceC.ETCUSD.perp": 10,
    "BinanceC.FILUSD.perp": 10,
    "BinanceC.EGLDUSD.perp": 10,
    "BinanceC.DOGEUSD.perp": 10,
    "BinanceC.UNIUSD.perp": 10,
    "BinanceC.THETAUSD.perp": 10,
    "BinanceC.XLMUSD.perp": 10,
    "BinanceC.SOLUSD.perp": 10,
    "BinanceC.FTMUSD.perp": 10,
    "BinanceC.SANDUSD.perp": 10,
    "BinanceC.MANAUSD.perp": 10,
    "BinanceC.AVAXUSD.perp": 10,
    "BinanceC.GALAUSD.perp": 10,
    "BinanceC.MATICUSD.perp": 10,
    "BinanceC.NEARUSD.perp": 10,
    "BinanceC.ATOMUSD.perp": 10,
    "BinanceC.AAVEUSD.perp": 10,
    "BinanceC.ADAUSD.quarter": 10,
    "BinanceC.LINKUSD.quarter": 10,
    "BinanceC.BCHUSD.quarter": 10,
    "BinanceC.DOTUSD.quarter": 10,
    "BinanceC.XRPUSD.quarter": 10,
    "BinanceC.LTCUSD.quarter": 10,
    "BinanceC.BNBUSD.quarter": 10,
    "BinanceC.CRVUSD.perp": 10,
    "BinanceC.AXSUSD.perp": 10,
    "BinanceC.ROSEUSD.perp": 10,
    "BinanceC.XTZUSD.perp": 10,
    "BinanceC.ICXUSD.perp": 10,
    "BinanceC.ALGOUSD.perp": 10,
    "BinanceC.RUNEUSD.perp": 10,
    "BinanceC.ADAUSD.next_quarter": 10,
    "BinanceC.LINKUSD.next_quarter": 10,
    "BinanceC.BCHUSD.next_quarter": 10,
    "BinanceC.DOTUSD.next_quarter": 10,
    "BinanceC.XRPUSD.next_quarter": 10,
    "BinanceC.LTCUSD.next_quarter": 10,
    "BinanceC.BNBUSD.next_quarter": 10,
    "BinanceC.APEUSD.perp": 10,
    "BinanceC.VETUSD.perp": 10,
    "BinanceC.ZILUSD.perp": 10,
    "BinanceC.KNCUSD.perp": 10,
    "BinanceC.XMRUSD.perp": 10,
    "BinanceC.GMTUSD.perp": 10,

    'Binance.BTCUSDT.spot': 1,
    'Binance.ETHUSDT.spot': 1,
    'Binance.BNBUSDT.spot': 1,
    'Binance.BTCBUSD.spot': 1,
    'Binance.ETHBUSD.spot': 1,
    'Binance.BNBBUSD.spot': 1,
    'Binance.ETHBTC.spot': 1,
    'Binance.BNBBTC.spot': 1,
    "Binance.LTCBTC.spot": 1,
    "Binance.LINKBTC.spot": 1,
    "Binance.EOSBTC.spot": 1,
    "Binance.ETCBTC.spot": 1,
    "Binance.TRXBTC.spot": 1,
    "Binance.XRPBTC.spot": 1,
    "Binance.XMRBTC.spot": 1,
    "Binance.MANABTC.spot": 1,
    "Binance.ADABTC.spot": 1,
    "Binance.LTCUSDT.spot": 1,
    "Binance.ADAUSDT.spot": 1,
    "Binance.XRPUSDT.spot": 1,
    "Binance.EOSUSDT.spot": 1,
    "Binance.TRXUSDT.spot": 1,
    "Binance.ETCUSDT.spot": 1,
    "Binance.LINKUSDT.spot": 1,
    "Binance.XMRUSDT.spot": 1,
    "Binance.MATICBTC.spot": 1,
    "Binance.MATICUSDT.spot": 1,
    "Binance.ATOMBTC.spot": 1,
    "Binance.ATOMUSDT.spot": 1,
    "Binance.FTMBTC.spot": 1,
    "Binance.FTMUSDT.spot": 1,
    "Binance.DOGEBTC.spot": 1,
    "Binance.DOGEUSDT.spot": 1,
    "Binance.BUSDUSDT.spot": 1,
    "Binance.XRPBUSD.spot": 1,
    "Binance.LTCBUSD.spot": 1,
    "Binance.LINKBUSD.spot": 1,
    "Binance.ETCBUSD.spot": 1,
    "Binance.TRXBUSD.spot": 1,
    "Binance.EOSBUSD.spot": 1,
    "Binance.ADABUSD.spot": 1,
    "Binance.BCHBTC.spot": 1,
    "Binance.BCHUSDT.spot": 1,
    "Binance.BCHBUSD.spot": 1,
    "Binance.FTTBTC.spot": 1,
    "Binance.FTTUSDT.spot": 1,
    "Binance.ATOMBUSD.spot": 1,
    "Binance.XMRBUSD.spot": 1,
    "Binance.SOLBTC.spot": 1,
    "Binance.SOLUSDT.spot": 1,
    "Binance.SOLBUSD.spot": 1,
    "Binance.MATICBUSD.spot": 1,
    "Binance.MANABUSD.spot": 1,
    "Binance.DOGEBUSD.spot": 1,
    "Binance.MANAUSDT.spot": 1,
    "Binance.SANDBTC.spot": 1,
    "Binance.SANDUSDT.spot": 1,
    "Binance.SANDBUSD.spot": 1,
    "Binance.DOTBTC.spot": 1,
    "Binance.DOTBUSD.spot": 1,
    "Binance.DOTUSDT.spot": 1,
    "Binance.EGLDBTC.spot": 1,
    "Binance.EGLDBUSD.spot": 1,
    "Binance.EGLDUSDT.spot": 1,
    "Binance.UNIBTC.spot": 1,
    "Binance.UNIBUSD.spot": 1,
    "Binance.UNIUSDT.spot": 1,
    "Binance.AVAXBTC.spot": 1,
    "Binance.AVAXBUSD.spot": 1,
    "Binance.AVAXUSDT.spot": 1,
    "Binance.NEARBTC.spot": 1,
    "Binance.NEARBUSD.spot": 1,
    "Binance.NEARUSDT.spot": 1,
    "Binance.AXSBTC.spot": 1,
    "Binance.AXSBUSD.spot": 1,
    "Binance.AXSUSDT.spot": 1,
    "Binance.FTMBUSD.spot": 1,
    "Binance.FTTBUSD.spot": 1,
    "Binance.GALAUSDT.spot": 1,
    "Binance.GALABUSD.spot": 1,
    "Binance.GALABTC.spot": 1,
    "Binance.GMTBTC.spot": 1,
    "Binance.GMTBUSD.spot": 1,
    "Binance.GMTUSDT.spot": 1,
    "Binance.APEUSDT.spot": 1,
    "Binance.APEBUSD.spot": 1,
    "Binance.APEBTC.spot": 1,
    "Binance.GALUSDT.spot": 1,
    "Binance.GALBUSD.spot": 1,
    "Binance.GALBTC.spot": 1,

    'HuobiFuture.BTCUSD.this_week': 100,
    'HuobiFuture.BTCUSD.next_week': 100,
    'HuobiFuture.BTCUSD.quarter': 100,
    'HuobiFuture.BTCUSD.next_quarter': 100,
    'HuobiFuture.ETHUSD.this_week': 10,
    'HuobiFuture.ETHUSD.next_week': 10,
    'HuobiFuture.ETHUSD.quarter': 10,
    'HuobiFuture.ETHUSD.next_quarter': 10,

    'Huobi.ETHBTC.spot': 1,
    'Huobi.ETHUSDT.spot': 1,
    'Huobi.BTCUSDT.spot': 1,

    'HuobiSwap.BTCUSD.perp': 100,
    'HuobiSwap.ETHUSD.perp': 10,
    'HuobiSwap.XRPUSD.perp': 10,
    'HuobiSwap.EOSUSD.perp': 10,
    'HuobiSwap.NEOUSD.perp': 10,
    'HuobiSwap.YFIIUSD.perp': 10,

    'HuobiSU.BTCUSDT.perp': 0.001,
    'HuobiSU.ETHUSDT.perp': 0.01,
    'HuobiSU.XRPUSDT.perp': 10,
    'HuobiSU.BNBUSDT.perp': 0.1,

    'Ftx.BTCUSD.perp': 1,
    'Ftx.BTCUSD.quarter': 1,
    'Ftx.BTCUSD.next_quarter': 1,
    'Ftx.ETHUSD.perp': 1,
    'Ftx.ETHUSD.quarter': 1,
    'Ftx.ETHUSD.next_quarter': 1,
    'Ftx.BNBUSD.perp': 1,
    'Ftx.BNBUSD.quarter': 1,
    'Ftx.FTTUSD.perp': 1,
    'Ftx.USDTUSD.perp': 1,
    'Ftx.USDTUSD.quarter': 1,
    'Ftx.USDTUSD.spot': 1,

    'BitMEX.BTCUSD.perp': 1,
    'BitMEX.BTCUSD.quarter': 1,
    'BitMEX.BTCUSD.next_quarter': 1,
    'BitMEX.ETHUSD.perp': 1e-6,
    'BitMEX.ETHUSD.quarter': 1e-6,
    'BitMEX.ETHUSD.next_quarter': 1e-6,
    'BitMEX.ETHBTC.quarter': 1,
    'BitMEX.ETHBTC.next_quarter': 1,

    'BitMEX.ADAUSD.perp': 1e-4,
    'BitMEX.AVAXUSD.perp': 1e-5,
    'BitMEX.AXSUSD.perp': 1e-6,
    'BitMEX.BCHUSD.perp': 1e-6,
    'BitMEX.BNBUSD.perp': 1e-6,
    'BitMEX.DOGEUSD.perp': 1e-6,
    'BitMEX.DOTUSD.perp': 1e-5,
    'BitMEX.EOSUSD.perp': 1e-4,
    'BitMEX.LINKUSD.perp': 1e-5,
    'BitMEX.LTCUSD.perp': 2e-6,
    'BitMEX.LUNAUSD.perp': 1e-5,
    'BitMEX.SOLUSD.perp': 1e-6,
    'BitMEX.XRPUSD.perp': 2e-4,

    'OKExC.BTCUSD.perp': 100,
    'OKExC.BTCUSD.this_week': 100,
    'OKExC.BTCUSD.next_week': 100,
    'OKExC.BTCUSD.quarter': 100,
    'OKExC.BTCUSD.next_quarter': 100,
    'OKExC.ETHUSD.perp': 10,
    'OKExC.ETHUSD.this_week': 10,
    'OKExC.ETHUSD.next_week': 10,
    'OKExC.ETHUSD.quarter': 10,
    'OKExC.ETHUSD.next_quarter': 10,

    'OKExU.BTCUSDT.perp': 0.01,
    'OKExU.BTCUSDT.this_week': 0.01,
    'OKExU.BTCUSDT.next_week': 0.01,
    'OKExU.BTCUSDT.quarter': 0.01,
    'OKExU.BTCUSDT.next_quarter': 0.01,
    'OKExU.ETHUSDT.perp': 0.1,
    'OKExU.ETHUSDT.this_week': 0.1,
    'OKExU.ETHUSDT.next_week': 0.1,
    'OKExU.ETHUSDT.quarter': 0.1,
    'OKExU.ETHUSDT.next_quarter': 0.1,

    'BybitC.BTCUSD.perp': 1,
    'BybitC.ETHUSD.perp': 1,

    'Deribit.BTCUSD.perp': 10,
    'Deribit.BTCUSD.quarter': 10,
    'Deribit.BTCUSD.next_quarter': 10,
    'Deribit.ETHUSD.perp': 1,
    'Deribit.ETHUSD.quarter': 1,
    'Deribit.ETHUSD.next_quarter': 1,
};

// TODO: quantity here just support integer, not good for USDT-margin contract and spot
QUANTITY_TICK_SIZE = {
    "BinanceC.BTCUSD.perp": 1,
    "BinanceC.BTCUSD.quarter": 1,
    "BinanceC.BTCUSD.next_quarter": 1,
    "BinanceC.ETHUSD.perp": 1,
    "BinanceC.ETHUSD.quarter": 1,
    "BinanceC.ETHUSD.next_quarter": 1,
    "BinanceC.LINKUSD.perp": 1,
    "BinanceC.BNBUSD.perp": 1,
    "BinanceC.TRXUSD.perp": 1,
    "BinanceC.DOTUSD.perp": 1,
    "BinanceC.ADAUSD.perp": 1,
    "BinanceC.EOSUSD.perp": 1,
    "BinanceC.LTCUSD.perp": 1,
    "BinanceC.BCHUSD.perp": 1,
    "BinanceC.XRPUSD.perp": 1,
    "BinanceC.ETCUSD.perp": 1,
    "BinanceC.FILUSD.perp": 1,
    "BinanceC.EGLDUSD.perp": 1,
    "BinanceC.DOGEUSD.perp": 1,
    "BinanceC.UNIUSD.perp": 1,
    "BinanceC.THETAUSD.perp": 1,
    "BinanceC.XLMUSD.perp": 1,
    "BinanceC.SOLUSD.perp": 1,
    "BinanceC.FTMUSD.perp": 1,
    "BinanceC.SANDUSD.perp": 1,
    "BinanceC.MANAUSD.perp": 1,
    "BinanceC.AVAXUSD.perp": 1,
    "BinanceC.GALAUSD.perp": 1,
    "BinanceC.MATICUSD.perp": 1,
    "BinanceC.NEARUSD.perp": 1,
    "BinanceC.ATOMUSD.perp": 1,
    "BinanceC.AAVEUSD.perp": 1,
    "BinanceC.ADAUSD.quarter": 1,
    "BinanceC.LINKUSD.quarter": 1,
    "BinanceC.BCHUSD.quarter": 1,
    "BinanceC.DOTUSD.quarter": 1,
    "BinanceC.XRPUSD.quarter": 1,
    "BinanceC.LTCUSD.quarter": 1,
    "BinanceC.BNBUSD.quarter": 1,
    "BinanceC.CRVUSD.perp": 1,
    "BinanceC.AXSUSD.perp": 1,
    "BinanceC.ROSEUSD.perp": 1,
    "BinanceC.XTZUSD.perp": 1,
    "BinanceC.ICXUSD.perp": 1,
    "BinanceC.ALGOUSD.perp": 1,
    "BinanceC.RUNEUSD.perp": 1,
    "BinanceC.ADAUSD.next_quarter": 1,
    "BinanceC.LINKUSD.next_quarter": 1,
    "BinanceC.BCHUSD.next_quarter": 1,
    "BinanceC.DOTUSD.next_quarter": 1,
    "BinanceC.XRPUSD.next_quarter": 1,
    "BinanceC.LTCUSD.next_quarter": 1,
    "BinanceC.BNBUSD.next_quarter": 1,
    "BinanceC.APEUSD.perp": 1,
    "BinanceC.VETUSD.perp": 1,
    "BinanceC.ZILUSD.perp": 1,
    "BinanceC.KNCUSD.perp": 1,
    "BinanceC.XMRUSD.perp": 1,
    "BinanceC.GMTUSD.perp": 1,

    'BinanceU.ETHUSDT.quarter': 0.001,
    'BinanceU.ETHUSDT.next_quarter': 0.001,
    'BinanceU.BTCUSDT.quarter': 0.001,
    'BinanceU.BTCUSDT.next_quarter': 0.001,

    'BinanceU.BTCUSDT.perp': 0.001,
    'BinanceU.ETHUSDT.perp': 0.001,
    "BinanceU.BNBUSDT.perp": 0.01,
    "BinanceU.FTTUSDT.perp": 0.1,
    "BinanceU.BCHUSDT.perp": 0.001,
    "BinanceU.XRPUSDT.perp": 0.1,
    "BinanceU.EOSUSDT.perp": 0.1,
    "BinanceU.LTCUSDT.perp": 0.001,
    "BinanceU.LTCBUSD.perp": 0.001,
    "BinanceU.TRXUSDT.perp": 1,
    "BinanceU.ETCUSDT.perp": 0.01,
    "BinanceU.LINKUSDT.perp": 0.01,
    "BinanceU.LINKBUSD.perp": 0.01,
    "BinanceU.XLMUSDT.perp": 1,
    "BinanceU.ADAUSDT.perp": 1,
    "BinanceU.XMRUSDT.perp": 0.001,
    "BinanceU.DASHUSDT.perp": 0.001,
    "BinanceU.ZECUSDT.perp": 0.001,
    "BinanceU.XTZUSDT.perp": 0.1,
    "BinanceU.ATOMUSDT.perp": 0.01,
    "BinanceU.ONTUSDT.perp": 0.1,
    "BinanceU.IOTAUSDT.perp": 0.1,
    "BinanceU.BATUSDT.perp": 0.1,
    "BinanceU.VETUSDT.perp": 1,
    "BinanceU.NEOUSDT.perp": 0.01,
    "BinanceU.QTUMUSDT.perp": 0.1,
    "BinanceU.IOSTUSDT.perp": 1,
    "BinanceU.THETAUSDT.perp": 0.1,
    "BinanceU.ALGOUSDT.perp": 0.1,
    "BinanceU.ZILUSDT.perp": 1,
    "BinanceU.KNCUSDT.perp": 1,
    "BinanceU.ZRXUSDT.perp": 0.1,
    "BinanceU.COMPUSDT.perp": 0.001,
    "BinanceU.OMGUSDT.perp": 0.1,
    "BinanceU.DOGEUSDT.perp": 1,
    "BinanceU.SXPUSDT.perp": 0.1,
    "BinanceU.KAVAUSDT.perp": 0.1,
    "BinanceU.BANDUSDT.perp": 0.1,
    "BinanceU.RLCUSDT.perp": 0.1,
    "BinanceU.WAVESUSDT.perp": 0.1,
    "BinanceU.WAVESBUSD.perp": 0.1,
    "BinanceU.MKRUSDT.perp": 0.001,
    "BinanceU.SNXUSDT.perp": 0.1,
    "BinanceU.DOTUSDT.perp": 0.1,
    "BinanceU.DEFIUSDT.perp": 0.001,
    "BinanceU.YFIUSDT.perp": 0.001,
    "BinanceU.BALUSDT.perp": 0.1,
    "BinanceU.CRVUSDT.perp": 0.1,
    "BinanceU.TRBUSDT.perp": 0.1,
    "BinanceU.RUNEUSDT.perp": 1,
    "BinanceU.SUSHIUSDT.perp": 1,
    "BinanceU.SRMUSDT.perp": 1,
    "BinanceU.EGLDUSDT.perp": 0.1,
    "BinanceU.SOLUSDT.perp": 1,
    "BinanceU.ICXUSDT.perp": 1,
    "BinanceU.STORJUSDT.perp": 1,
    "BinanceU.BLZUSDT.perp": 1,
    "BinanceU.UNIUSDT.perp": 1,
    "BinanceU.AVAXUSDT.perp": 1,
    "BinanceU.FTMUSDT.perp": 1,
    "BinanceU.HNTUSDT.perp": 1,
    "BinanceU.ENJUSDT.perp": 1,
    "BinanceU.FLMUSDT.perp": 1,
    "BinanceU.TOMOUSDT.perp": 1,
    "BinanceU.RENUSDT.perp": 1,
    "BinanceU.KSMUSDT.perp": 0.1,
    "BinanceU.NEARUSDT.perp": 1,
    "BinanceU.AAVEUSDT.perp": 0.1,
    "BinanceU.FILUSDT.perp": 0.1,
    "BinanceU.RSRUSDT.perp": 1,
    "BinanceU.LRCUSDT.perp": 1,
    "BinanceU.MATICUSDT.perp": 1,
    "BinanceU.MATICBUSD.perp": 1,
    "BinanceU.OCEANUSDT.perp": 1,
    "BinanceU.CVCUSDT.perp": 1,
    "BinanceU.BELUSDT.perp": 1,
    "BinanceU.CTKUSDT.perp": 1,
    "BinanceU.AXSUSDT.perp": 1,
    "BinanceU.ALPHAUSDT.perp": 1,
    "BinanceU.ZENUSDT.perp": 0.1,
    "BinanceU.SKLUSDT.perp": 1,
    "BinanceU.GRTUSDT.perp": 1,
    "BinanceU.1INCHUSDT.perp": 1,
    "BinanceU.BTCBUSD.perp": 0.001,
    "BinanceU.CHZUSDT.perp": 1,
    "BinanceU.SANDUSDT.perp": 1,
    "BinanceU.SANDBUSD.perp": 1,
    "BinanceU.ANKRUSDT.perp": 1,
    "BinanceU.BTSUSDT.perp": 1,
    "BinanceU.LITUSDT.perp": 0.1,
    "BinanceU.UNFIUSDT.perp": 0.1,
    "BinanceU.REEFUSDT.perp": 1,
    "BinanceU.RVNUSDT.perp": 1,
    "BinanceU.SFPUSDT.perp": 1,
    "BinanceU.XEMUSDT.perp": 1,
    "BinanceU.BTCSTUSDT.perp": 0.1,
    "BinanceU.COTIUSDT.perp": 1,
    "BinanceU.CHRUSDT.perp": 1,
    "BinanceU.MANAUSDT.perp": 1,
    "BinanceU.ALICEUSDT.perp": 0.1,
    "BinanceU.HBARUSDT.perp": 1,
    "BinanceU.ONEUSDT.perp": 1,
    "BinanceU.LINAUSDT.perp": 1,
    "BinanceU.STMXUSDT.perp": 1,
    "BinanceU.DENTUSDT.perp": 1,
    "BinanceU.CELRUSDT.perp": 1,
    "BinanceU.HOTUSDT.perp": 1,
    "BinanceU.MTLUSDT.perp": 1,
    "BinanceU.OGNUSDT.perp": 1,
    "BinanceU.NKNUSDT.perp": 1,
    "BinanceU.SCUSDT.perp": 1,
    "BinanceU.DGBUSDT.perp": 1,
    "BinanceU.1000SHIBUSDT.perp": 1,
    "BinanceU.ICPUSDT.perp": 0.01,
    "BinanceU.BAKEUSDT.perp": 1,
    "BinanceU.GTCUSDT.perp": 0.1,
    "BinanceU.ETHBUSD.perp": 0.001,
    "BinanceU.BTCDOMUSDT.perp": 0.001,
    "BinanceU.TLMUSDT.perp": 1,
    "BinanceU.BNBBUSD.perp": 0.01,
    "BinanceU.ADABUSD.perp": 1,
    "BinanceU.XRPBUSD.perp": 0.1,
    "BinanceU.IOTXUSDT.perp": 1,
    "BinanceU.DOGEBUSD.perp": 1,
    "BinanceU.AUDIOUSDT.perp": 1,
    "BinanceU.RAYUSDT.perp": 0.1,
    "BinanceU.C98USDT.perp": 1,
    "BinanceU.MASKUSDT.perp": 1,
    "BinanceU.ATAUSDT.perp": 1,
    "BinanceU.SOLBUSD.perp": 1,
    "BinanceU.FTTBUSD.perp": 0.1,
    "BinanceU.DYDXUSDT.perp": 0.1,
    "BinanceU.1000XECUSDT.perp": 1,
    "BinanceU.GALAUSDT.perp": 1,
    "BinanceU.CELOUSDT.perp": 0.1,
    "BinanceU.ARUSDT.perp": 0.1,
    "BinanceU.KLAYUSDT.perp": 0.1,
    "BinanceU.ARPAUSDT.perp": 1,
    "BinanceU.CTSIUSDT.perp": 1,
    "BinanceU.LPTUSDT.perp": 0.1,
    "BinanceU.ENSUSDT.perp": 0.1,
    "BinanceU.PEOPLEUSDT.perp": 1,
    "BinanceU.ANTUSDT.perp": 0.1,
    "BinanceU.ROSEUSDT.perp": 1,
    "BinanceU.DUSKUSDT.perp": 1,
    "BinanceU.FLOWUSDT.perp": 0.1,
    "BinanceU.IMXUSDT.perp": 1,
    "BinanceU.API3USDT.perp": 0.1,
    "BinanceU.GMTUSDT.perp": 1,
    "BinanceU.APEUSDT.perp": 1,
    "BinanceU.BNXUSDT.perp": 0.1,
    "BinanceU.WOOUSDT.perp": 1,
    "BinanceU.JASMYUSDT.perp": 1,
    "BinanceU.DARUSDT.perp": 0.1,
    "BinanceU.GALUSDT.perp": 1,
    "BinanceU.AVAXBUSD.perp": 0.1,
    "BinanceU.NEARBUSD.perp": 0.1,
    "BinanceU.GMTBUSD.perp": 0.1,
    "BinanceU.APEBUSD.perp": 0.1,
    "BinanceU.GALBUSD.perp": 1,
    "BinanceU.FTMBUSD.perp": 1,
    "BinanceU.DODOBUSD.perp": 1,
    "BinanceU.ANCBUSD.perp": 1,
    "BinanceU.GALABUSD.perp": 1,
    "BinanceU.TRXBUSD.perp": 1,
    "BinanceU.1000LUNCBUSD.perp": 1,
    "BinanceU.DOTBUSD.perp": 0.1,
    "BinanceU.QNTUSDT.perp": 0.1,
    "BinanceU.STGUSDT.perp": 1,

    'Binance.BTCUSDT.spot': 0.00001,
    'Binance.ETHUSDT.spot': 0.0001,
    'Binance.BNBUSDT.spot': 0.001,
    'Binance.BTCBUSD.spot': 0.00001,
    'Binance.ETHBUSD.spot': 0.0001,
    'Binance.BNBBUSD.spot': 0.001,
    'Binance.ETHBTC.spot': 0.0001,
    'Binance.BNBBTC.spot': 0.001,
    "Binance.LTCBTC.spot": 0.001,
    "Binance.LINKBTC.spot": 0.01,
    "Binance.EOSBTC.spot": 0.1,
    "Binance.ETCBTC.spot": 0.01,
    "Binance.TRXBTC.spot": 1,
    "Binance.XRPBTC.spot": 1,
    "Binance.XMRBTC.spot": 0.001,
    "Binance.MANABTC.spot": 1,
    "Binance.ADABTC.spot": 0.1,
    "Binance.LTCUSDT.spot": 0.001,
    "Binance.ADAUSDT.spot": 0.1,
    "Binance.XRPUSDT.spot": 1,
    "Binance.EOSUSDT.spot": 0.1,
    "Binance.TRXUSDT.spot": 0.1,
    "Binance.ETCUSDT.spot": 0.01,
    "Binance.LINKUSDT.spot": 0.01,
    "Binance.XMRUSDT.spot": 0.001,
    "Binance.MATICBTC.spot": 0.1,
    "Binance.MATICUSDT.spot": 0.1,
    "Binance.ATOMBTC.spot": 0.01,
    "Binance.ATOMUSDT.spot": 0.01,
    "Binance.FTMBTC.spot": 1,
    "Binance.FTMUSDT.spot": 1,
    "Binance.DOGEBTC.spot": 1,
    "Binance.DOGEUSDT.spot": 1,
    "Binance.BUSDUSDT.spot": 1,
    "Binance.XRPBUSD.spot": 1,
    "Binance.LTCBUSD.spot": 0.001,
    "Binance.LINKBUSD.spot": 0.01,
    "Binance.ETCBUSD.spot": 0.01,
    "Binance.TRXBUSD.spot": 0.1,
    "Binance.EOSBUSD.spot": 0.1,
    "Binance.ADABUSD.spot": 0.1,
    "Binance.BCHBTC.spot": 0.001,
    "Binance.BCHUSDT.spot": 0.001,
    "Binance.BCHBUSD.spot": 0.001,
    "Binance.FTTBTC.spot": 0.01,
    "Binance.FTTUSDT.spot": 0.01,
    "Binance.ATOMBUSD.spot": 0.01,
    "Binance.XMRBUSD.spot": 0.001,
    "Binance.SOLBTC.spot": 0.01,
    "Binance.SOLUSDT.spot": 0.01,
    "Binance.SOLBUSD.spot": 0.01,
    "Binance.MATICBUSD.spot": 0.1,
    "Binance.MANABUSD.spot": 1,
    "Binance.DOGEBUSD.spot": 1,
    "Binance.MANAUSDT.spot": 1,
    "Binance.SANDBTC.spot": 1,
    "Binance.SANDUSDT.spot": 1,
    "Binance.SANDBUSD.spot": 1,
    "Binance.DOTBTC.spot": 0.01,
    "Binance.DOTBUSD.spot": 0.01,
    "Binance.DOTUSDT.spot": 0.01,
    "Binance.EGLDBTC.spot": 0.01,
    "Binance.EGLDBUSD.spot": 0.01,
    "Binance.EGLDUSDT.spot": 0.01,
    "Binance.UNIBTC.spot": 0.01,
    "Binance.UNIBUSD.spot": 0.01,
    "Binance.UNIUSDT.spot": 0.01,
    "Binance.AVAXBTC.spot": 0.01,
    "Binance.AVAXBUSD.spot": 0.01,
    "Binance.AVAXUSDT.spot": 0.01,
    "Binance.NEARBTC.spot": 0.1,
    "Binance.NEARBUSD.spot": 0.1,
    "Binance.NEARUSDT.spot": 0.1,
    "Binance.AXSBTC.spot": 0.01,
    "Binance.AXSBUSD.spot": 0.01,
    "Binance.AXSUSDT.spot": 0.01,
    "Binance.FTMBUSD.spot": 1,
    "Binance.FTTBUSD.spot": 0.01,
    "Binance.GALAUSDT.spot": 1,
    "Binance.GALABUSD.spot": 1,
    "Binance.GALABTC.spot": 1,
    "Binance.GMTBTC.spot": 0.1,
    "Binance.GMTBUSD.spot": 0.1,
    "Binance.GMTUSDT.spot": 0.1,
    "Binance.APEUSDT.spot": 0.01,
    "Binance.APEBUSD.spot": 0.01,
    "Binance.APEBTC.spot": 0.01,
    "Binance.GALUSDT.spot": 0.001,
    "Binance.GALBUSD.spot": 0.001,
    "Binance.GALBTC.spot": 0.001,

    'Ftx.BTCUSD.perp': 0.0001,
    'Ftx.BTCUSD.quarter': 0.0001,
    'Ftx.BTCUSD.next_quarter': 0.0001,
    'Ftx.ETHUSD.perp': 0.001,
    'Ftx.ETHUSD.quarter': 0.001,
    'Ftx.ETHUSD.next_quarter': 0.001,
    'Ftx.BNBUSD.perp': 0.1,
    'Ftx.BNBUSD.quarter': 0.1,
    'Ftx.FTTUSD.perp': 0.1,
    'Ftx.USDTUSD.perp': 1,
    'Ftx.USDTUSD.quarter': 1,
    'Ftx.USDTUSD.spot': 1,

    'HuobiSwap.BTCUSD.perp': 1,
    'HuobiSwap.ETHUSD.perp': 1,
    'HuobiSwap.XRPUSD.perp': 1,
    'HuobiSwap.EOSUSD.perp': 1,
    'HuobiSwap.NEOUSD.perp': 1,

    'HuobiSU.BTCUSDT.perp': 1,
    'HuobiSU.ETHUSDT.perp': 1,
    'HuobiSU.XRPUSDT.perp': 1,
    'HuobiSU.BNBUSDT.perp': 1,

    'HuobiFuture.BTCUSD.this_week': 1,
    'HuobiFuture.BTCUSD.next_week': 1,
    'HuobiFuture.BTCUSD.quarter': 1,
    'HuobiFuture.BTCUSD.next_quarter': 1,
    'HuobiFuture.ETHUSD.this_week': 1,
    'HuobiFuture.ETHUSD.next_week': 1,
    'HuobiFuture.ETHUSD.quarter': 1,
    'HuobiFuture.ETHUSD.next_quarter': 1,

    'Huobi.ETHBTC.spot': 0.0001,
    'Huobi.ETHUSDT.spot': 0.001,
    'Huobi.BTCUSDT.spot': 0.0001,

    'BitMEX.ETHUSD.perp': 1,
    'BitMEX.ETHUSD.quarter': 1,
    'BitMEX.ETHUSD.next_quarter': 1,
    'BitMEX.ETHBTC.quarter': 1,
    'BitMEX.ETHBTC.next_quarter': 1,
    'BitMEX.BTCUSD.perp': 100,
    'BitMEX.BTCUSD.quarter': 100,
    'BitMEX.BTCUSD.next_quarter': 100,
    'BitMEX.XRPUSD.perp': 1,
    'BitMEX.XRPBTC.quarter': 1,
    'BitMEX.XRPBTC.next_quarter': 1,

    'BitMEX.ADAUSD.perp': 1,
    'BitMEX.AVAXUSD.perp': 1,
    'BitMEX.AXSUSD.perp': 1,
    'BitMEX.BCHUSD.perp': 1,
    'BitMEX.BNBUSD.perp': 1,
    'BitMEX.DOGEUSD.perp': 1,
    'BitMEX.DOTUSD.perp': 1,
    'BitMEX.EOSUSD.perp': 1,
    'BitMEX.LINKUSD.perp': 1,
    'BitMEX.LTCUSD.perp': 1,
    'BitMEX.LUNAUSD.perp': 1,
    'BitMEX.SOLUSD.perp': 1,

    'OKX.CRVUSDT.perp': 1,

    'OKExC.BTCUSD.perp': 1,
    'OKExC.BTCUSD.this_week': 1,
    'OKExC.BTCUSD.next_week': 1,
    'OKExC.BTCUSD.quarter': 1,
    'OKExC.BTCUSD.next_quarter': 1,
    'OKExC.ETHUSD.perp': 1,
    'OKExC.ETHUSD.this_week': 1,
    'OKExC.ETHUSD.next_week': 1,
    'OKExC.ETHUSD.quarter': 1,
    'OKExC.ETHUSD.next_quarter': 1,

    'OKExU.BTCUSDT.perp': 1,
    'OKExU.BTCUSDT.this_week': 1,
    'OKExU.BTCUSDT.next_week': 1,
    'OKExU.BTCUSDT.quarter': 1,
    'OKExU.BTCUSDT.next_quarter': 1,
    'OKExU.ETHUSDT.perp': 1,
    'OKExU.ETHUSDT.this_week': 1,
    'OKExU.ETHUSDT.next_week': 1,
    'OKExU.ETHUSDT.quarter': 1,
    'OKExU.ETHUSDT.next_quarter': 1,

    'BybitC.BTCUSD.perp': 1,
    'BybitC.ETHUSD.perp': 1,

    'Deribit.BTCUSD.perp': 1,
    'Deribit.BTCUSD.quarter': 1,
    'Deribit.BTCUSD.next_quarter': 1,
    'Deribit.ETHUSD.perp': 1,
    'Deribit.ETHUSD.quarter': 1,
    'Deribit.ETHUSD.next_quarter': 1,

    'Deribit.BTCUSD.option': 0.1,
    'Deribit.ETHUSD.option': 1,
};

MIN_ORDER_SIZE = {
    'BinanceU.ETHUSDT.perp': 0.001,
    'BinanceU.ETHUSDT.quarter': 0.001,
    'BinanceU.ETHUSDT.next_quarter': 0.001,
    'BinanceU.BNBUSDT.perp': 0.001,
    'BinanceU.XRPUSDT.perp': 0.001,
    'BinanceU.FTTUSDT.perp': 0.001,
};

PRICE_TICK_SIZE = {
    "BinanceC.BTCUSD.perp": 0.1,
    "BinanceC.BTCUSD.quarter": 0.1,
    "BinanceC.BTCUSD.next_quarter": 0.1,
    "BinanceC.ETHUSD.perp": 0.01,
    "BinanceC.ETHUSD.quarter": 0.01,
    "BinanceC.ETHUSD.next_quarter": 0.01,
    "BinanceC.LINKUSD.perp": 0.001,
    "BinanceC.BNBUSD.perp": 0.001,
    "BinanceC.TRXUSD.perp": 0.00001,
    "BinanceC.DOTUSD.perp": 0.001,
    "BinanceC.ADAUSD.perp": 0.00001,
    "BinanceC.EOSUSD.perp": 0.001,
    "BinanceC.LTCUSD.perp": 0.01,
    "BinanceC.BCHUSD.perp": 0.01,
    "BinanceC.XRPUSD.perp": 0.0001,
    "BinanceC.ETCUSD.perp": 0.001,
    "BinanceC.FILUSD.perp": 0.001,
    "BinanceC.EGLDUSD.perp": 0.001,
    "BinanceC.DOGEUSD.perp": 0.000001,
    "BinanceC.UNIUSD.perp": 0.001,
    "BinanceC.THETAUSD.perp": 0.001,
    "BinanceC.XLMUSD.perp": 0.00001,
    "BinanceC.SOLUSD.perp": 0.001,
    "BinanceC.FTMUSD.perp": 0.0001,
    "BinanceC.SANDUSD.perp": 0.0001,
    "BinanceC.MANAUSD.perp": 0.0001,
    "BinanceC.AVAXUSD.perp": 0.01,
    "BinanceC.GALAUSD.perp": 0.00001,
    "BinanceC.MATICUSD.perp": 0.0001,
    "BinanceC.NEARUSD.perp": 0.001,
    "BinanceC.ATOMUSD.perp": 0.001,
    "BinanceC.AAVEUSD.perp": 0.01,
    "BinanceC.ADAUSD.quarter": 0.00001,
    "BinanceC.LINKUSD.quarter": 0.001,
    "BinanceC.BCHUSD.quarter": 0.01,
    "BinanceC.DOTUSD.quarter": 0.001,
    "BinanceC.XRPUSD.quarter": 0.0001,
    "BinanceC.LTCUSD.quarter": 0.01,
    "BinanceC.BNBUSD.quarter": 0.001,
    "BinanceC.CRVUSD.perp": 0.001,
    "BinanceC.AXSUSD.perp": 0.001,
    "BinanceC.ROSEUSD.perp": 0.00001,
    "BinanceC.XTZUSD.perp": 0.001,
    "BinanceC.ICXUSD.perp": 0.0001,
    "BinanceC.ALGOUSD.perp": 0.0001,
    "BinanceC.RUNEUSD.perp": 0.001,
    "BinanceC.ADAUSD.next_quarter": 0.00001,
    "BinanceC.LINKUSD.next_quarter": 0.001,
    "BinanceC.BCHUSD.next_quarter": 0.01,
    "BinanceC.DOTUSD.next_quarter": 0.001,
    "BinanceC.XRPUSD.next_quarter": 0.0001,
    "BinanceC.LTCUSD.next_quarter": 0.01,
    "BinanceC.BNBUSD.next_quarter": 0.001,
    "BinanceC.APEUSD.perp": 0.001,
    "BinanceC.VETUSD.perp": 0.00001,
    "BinanceC.ZILUSD.perp": 0.00001,
    "BinanceC.KNCUSD.perp": 0.001,
    "BinanceC.XMRUSD.perp": 0.01,
    "BinanceC.GMTUSD.perp": 0.001,

    'BinanceU.BTCUSDT.perp': 0.1,
    'BinanceU.BTCUSDT.quarter': 0.1,
    'BinanceU.BTCUSDT.next_quarter': 0.1,
    'BinanceU.ETHUSDT.perp': 0.01,
    'BinanceU.ETHUSDT.quarter': 0.01,
    'BinanceU.ETHUSDT.next_quarter': 0.01,
    'BinanceU.BNBUSDT.perp': 0.01,
    'BinanceU.FTTUSDT.perp': 0.001,
    "BinanceU.BCHUSDT.perp": 0.01,
    "BinanceU.XRPUSDT.perp": 0.0001,
    "BinanceU.EOSUSDT.perp": 0.001,
    "BinanceU.LTCUSDT.perp": 0.01,
    "BinanceU.LTCBUSD.perp": 0.01,
    "BinanceU.TRXUSDT.perp": 0.00001,
    "BinanceU.ETCUSDT.perp": 0.001,
    "BinanceU.LINKUSDT.perp": 0.001,
    "BinanceU.LINKBUSD.perp": 0.001,
    "BinanceU.XLMUSDT.perp": 0.00001,
    "BinanceU.ADAUSDT.perp": 0.0001,
    "BinanceU.XMRUSDT.perp": 0.01,
    "BinanceU.DASHUSDT.perp": 0.01,
    "BinanceU.ZECUSDT.perp": 0.01,
    "BinanceU.XTZUSDT.perp": 0.001,
    "BinanceU.ATOMUSDT.perp": 0.001,
    "BinanceU.ONTUSDT.perp": 0.0001,
    "BinanceU.IOTAUSDT.perp": 0.0001,
    "BinanceU.BATUSDT.perp": 0.0001,
    "BinanceU.VETUSDT.perp": 0.00001,
    "BinanceU.NEOUSDT.perp": 0.001,
    "BinanceU.QTUMUSDT.perp": 0.001,
    "BinanceU.IOSTUSDT.perp": 0.000001,
    "BinanceU.THETAUSDT.perp": 0.001,
    "BinanceU.ALGOUSDT.perp": 0.0001,
    "BinanceU.ZILUSDT.perp": 0.00001,
    "BinanceU.KNCUSDT.perp": 0.001,
    "BinanceU.ZRXUSDT.perp": 0.0001,
    "BinanceU.COMPUSDT.perp": 0.01,
    "BinanceU.OMGUSDT.perp": 0.001,
    "BinanceU.DOGEUSDT.perp": 0.00001,
    "BinanceU.SXPUSDT.perp": 0.0001,
    "BinanceU.KAVAUSDT.perp": 0.0001,
    "BinanceU.BANDUSDT.perp": 0.0001,
    "BinanceU.RLCUSDT.perp": 0.0001,
    "BinanceU.WAVESUSDT.perp": 0.001,
    "BinanceU.WAVESBUSD.perp": 0.001,
    "BinanceU.MKRUSDT.perp": 0.1,
    "BinanceU.SNXUSDT.perp": 0.001,
    "BinanceU.DOTUSDT.perp": 0.001,
    "BinanceU.DEFIUSDT.perp": 0.1,
    "BinanceU.YFIUSDT.perp": 1,
    "BinanceU.BALUSDT.perp": 0.001,
    "BinanceU.CRVUSDT.perp": 0.001,
    "BinanceU.TRBUSDT.perp": 0.01,
    "BinanceU.RUNEUSDT.perp": 0.001,
    "BinanceU.SUSHIUSDT.perp": 0.001,
    "BinanceU.SRMUSDT.perp": 0.001,
    "BinanceU.EGLDUSDT.perp": 0.01,
    "BinanceU.SOLUSDT.perp": 0.01,
    "BinanceU.ICXUSDT.perp": 0.0001,
    "BinanceU.STORJUSDT.perp": 0.0001,
    "BinanceU.BLZUSDT.perp": 0.00001,
    "BinanceU.UNIUSDT.perp": 0.001,
    "BinanceU.AVAXUSDT.perp": 0.01,
    "BinanceU.FTMUSDT.perp": 0.0001,
    "BinanceU.HNTUSDT.perp": 0.001,
    "BinanceU.ENJUSDT.perp": 0.0001,
    "BinanceU.FLMUSDT.perp": 0.0001,
    "BinanceU.TOMOUSDT.perp": 0.0001,
    "BinanceU.RENUSDT.perp": 0.0001,
    "BinanceU.KSMUSDT.perp": 0.01,
    "BinanceU.NEARUSDT.perp": 0.001,
    "BinanceU.AAVEUSDT.perp": 0.01,
    "BinanceU.FILUSDT.perp": 0.001,
    "BinanceU.RSRUSDT.perp": 0.000001,
    "BinanceU.LRCUSDT.perp": 0.0001,
    "BinanceU.MATICUSDT.perp": 0.0001,
    "BinanceU.MATICBUSD.perp": 0.0001,
    "BinanceU.OCEANUSDT.perp": 0.0001,
    "BinanceU.CVCUSDT.perp": 0.00001,
    "BinanceU.BELUSDT.perp": 0.0001,
    "BinanceU.CTKUSDT.perp": 0.0001,
    "BinanceU.AXSUSDT.perp": 0.001,
    "BinanceU.ALPHAUSDT.perp": 0.0001,
    "BinanceU.ZENUSDT.perp": 0.001,
    "BinanceU.SKLUSDT.perp": 0.00001,
    "BinanceU.GRTUSDT.perp": 0.00001,
    "BinanceU.1INCHUSDT.perp": 0.0001,
    "BinanceU.BTCBUSD.perp": 0.1,
    "BinanceU.CHZUSDT.perp": 0.00001,
    "BinanceU.SANDUSDT.perp": 0.0001,
    "BinanceU.SANDBUSD.perp": 0.0001,
    "BinanceU.ANKRUSDT.perp": 0.00001,
    "BinanceU.BTSUSDT.perp": 0.00001,
    "BinanceU.LITUSDT.perp": 0.001,
    "BinanceU.UNFIUSDT.perp": 0.001,
    "BinanceU.REEFUSDT.perp": 0.000001,
    "BinanceU.RVNUSDT.perp": 0.00001,
    "BinanceU.SFPUSDT.perp": 0.0001,
    "BinanceU.XEMUSDT.perp": 0.0001,
    "BinanceU.BTCSTUSDT.perp": 0.001,
    "BinanceU.COTIUSDT.perp": 0.00001,
    "BinanceU.CHRUSDT.perp": 0.0001,
    "BinanceU.MANAUSDT.perp": 0.0001,
    "BinanceU.ALICEUSDT.perp": 0.001,
    "BinanceU.HBARUSDT.perp": 0.00001,
    "BinanceU.ONEUSDT.perp": 0.00001,
    "BinanceU.LINAUSDT.perp": 0.00001,
    "BinanceU.STMXUSDT.perp": 0.00001,
    "BinanceU.DENTUSDT.perp": 0.000001,
    "BinanceU.CELRUSDT.perp": 0.00001,
    "BinanceU.HOTUSDT.perp": 0.000001,
    "BinanceU.MTLUSDT.perp": 0.0001,
    "BinanceU.OGNUSDT.perp": 0.0001,
    "BinanceU.NKNUSDT.perp": 0.00001,
    "BinanceU.SCUSDT.perp": 0.000001,
    "BinanceU.DGBUSDT.perp": 0.00001,
    "BinanceU.1000SHIBUSDT.perp": 0.000001,
    "BinanceU.ICPUSDT.perp": 0.01,
    "BinanceU.BAKEUSDT.perp": 0.0001,
    "BinanceU.GTCUSDT.perp": 0.001,
    "BinanceU.ETHBUSD.perp": 0.01,
    "BinanceU.BTCDOMUSDT.perp": 0.1,
    "BinanceU.TLMUSDT.perp": 0.0001,
    "BinanceU.BNBBUSD.perp": 0.01,
    "BinanceU.ADABUSD.perp": 0.0001,
    "BinanceU.XRPBUSD.perp": 0.0001,
    "BinanceU.IOTXUSDT.perp": 0.00001,
    "BinanceU.DOGEBUSD.perp": 0.00001,
    "BinanceU.AUDIOUSDT.perp": 0.0001,
    "BinanceU.RAYUSDT.perp": 0.001,
    "BinanceU.C98USDT.perp": 0.0001,
    "BinanceU.MASKUSDT.perp": 0.001,
    "BinanceU.ATAUSDT.perp": 0.0001,
    "BinanceU.SOLBUSD.perp": 0.01,
    "BinanceU.FTTBUSD.perp": 0.001,
    "BinanceU.DYDXUSDT.perp": 0.001,
    "BinanceU.1000XECUSDT.perp": 0.00001,
    "BinanceU.GALAUSDT.perp": 0.00001,
    "BinanceU.CELOUSDT.perp": 0.001,
    "BinanceU.ARUSDT.perp": 0.001,
    "BinanceU.KLAYUSDT.perp": 0.0001,
    "BinanceU.ARPAUSDT.perp": 0.00001,
    "BinanceU.CTSIUSDT.perp": 0.0001,
    "BinanceU.LPTUSDT.perp": 0.001,
    "BinanceU.ENSUSDT.perp": 0.001,
    "BinanceU.PEOPLEUSDT.perp": 0.00001,
    "BinanceU.ANTUSDT.perp": 0.001,
    "BinanceU.ROSEUSDT.perp": 0.00001,
    "BinanceU.DUSKUSDT.perp": 0.00001,
    "BinanceU.FLOWUSDT.perp": 0.001,
    "BinanceU.IMXUSDT.perp": 0.0001,
    "BinanceU.API3USDT.perp": 0.001,
    "BinanceU.GMTUSDT.perp": 0.0001,
    "BinanceU.APEUSDT.perp": 0.001,
    "BinanceU.BNXUSDT.perp": 0.01,
    "BinanceU.WOOUSDT.perp": 0.00001,
    "BinanceU.JASMYUSDT.perp": 0.00001,
    "BinanceU.DARUSDT.perp": 0.0001,
    "BinanceU.GALUSDT.perp": 0.0001,
    "BinanceU.AVAXBUSD.perp": 0.001,
    "BinanceU.NEARBUSD.perp": 0.001,
    "BinanceU.GMTBUSD.perp": 0.0001,
    "BinanceU.APEBUSD.perp": 0.001,
    "BinanceU.GALBUSD.perp": 0.001,
    "BinanceU.FTMBUSD.perp": 0.0001,
    "BinanceU.DODOBUSD.perp": 0.0001,
    "BinanceU.ANCBUSD.perp": 0.0001,
    "BinanceU.GALABUSD.perp": 0.000001,
    "BinanceU.TRXBUSD.perp": 0.000001,
    "BinanceU.1000LUNCBUSD.perp": 0.0001,
    "BinanceU.DOTBUSD.perp": 0.001,
    "BinanceU.QNTUSDT.perp": 0.01,
    "BinanceU.STGUSDT.perp": 0.0001,

    'Binance.BTCUSDT.spot': 0.01,
    'Binance.ETHUSDT.spot': 0.01,
    'Binance.BNBUSDT.spot': 0.1,
    'Binance.BTCBUSD.spot': 0.01,
    'Binance.ETHBUSD.spot': 0.01,
    'Binance.BNBBUSD.spot': 0.1,
    'Binance.ETHBTC.spot': 0.000001,
    'Binance.BNBBTC.spot': 0.000001,
    "Binance.LTCBTC.spot": 0.000001,
    "Binance.LINKBTC.spot": 1e-7,
    "Binance.EOSBTC.spot": 1e-7,
    "Binance.ETCBTC.spot": 0.000001,
    "Binance.TRXBTC.spot": 1e-8,
    "Binance.XRPBTC.spot": 1e-8,
    "Binance.XMRBTC.spot": 0.000001,
    "Binance.MANABTC.spot": 1e-8,
    "Binance.ADABTC.spot": 1e-8,
    "Binance.LTCUSDT.spot": 0.01,
    "Binance.ADAUSDT.spot": 0.0001,
    "Binance.XRPUSDT.spot": 0.0001,
    "Binance.EOSUSDT.spot": 0.001,
    "Binance.TRXUSDT.spot": 0.00001,
    "Binance.ETCUSDT.spot": 0.01,
    "Binance.LINKUSDT.spot": 0.01,
    "Binance.XMRUSDT.spot": 0.1,
    "Binance.MATICBTC.spot": 1e-8,
    "Binance.MATICUSDT.spot": 0.001,
    "Binance.ATOMBTC.spot": 1e-7,
    "Binance.ATOMUSDT.spot": 0.01,
    "Binance.FTMBTC.spot": 1e-8,
    "Binance.FTMUSDT.spot": 0.0001,
    "Binance.DOGEBTC.spot": 1e-8,
    "Binance.DOGEUSDT.spot": 0.00001,
    "Binance.BUSDUSDT.spot": 0.0001,
    "Binance.XRPBUSD.spot": 0.0001,
    "Binance.LTCBUSD.spot": 0.01,
    "Binance.LINKBUSD.spot": 0.01,
    "Binance.ETCBUSD.spot": 0.01,
    "Binance.TRXBUSD.spot": 0.00001,
    "Binance.EOSBUSD.spot": 0.001,
    "Binance.ADABUSD.spot": 0.0001,
    "Binance.BCHBTC.spot": 0.00001,
    "Binance.BCHUSDT.spot": 0.1,
    "Binance.BCHBUSD.spot": 0.1,
    "Binance.FTTBTC.spot": 1e-7,
    "Binance.FTTUSDT.spot": 0.01,
    "Binance.ATOMBUSD.spot": 0.01,
    "Binance.XMRBUSD.spot": 0.1,
    "Binance.SOLBTC.spot": 1e-7,
    "Binance.SOLUSDT.spot": 0.01,
    "Binance.SOLBUSD.spot": 0.01,
    "Binance.MATICBUSD.spot": 0.001,
    "Binance.MANABUSD.spot": 0.0001,
    "Binance.DOGEBUSD.spot": 0.00001,
    "Binance.MANAUSDT.spot": 0.0001,
    "Binance.SANDBTC.spot": 1e-8,
    "Binance.SANDUSDT.spot": 0.0001,
    "Binance.SANDBUSD.spot": 0.0001,
    "Binance.DOTBTC.spot": 1e-7,
    "Binance.DOTBUSD.spot": 0.01,
    "Binance.DOTUSDT.spot": 0.01,
    "Binance.EGLDBTC.spot": 0.000001,
    "Binance.EGLDBUSD.spot": 0.01,
    "Binance.EGLDUSDT.spot": 0.01,
    "Binance.UNIBTC.spot": 1e-7,
    "Binance.UNIBUSD.spot": 0.01,
    "Binance.UNIUSDT.spot": 0.01,
    "Binance.AVAXBTC.spot": 1e-7,
    "Binance.AVAXBUSD.spot": 0.01,
    "Binance.AVAXUSDT.spot": 0.01,
    "Binance.NEARBTC.spot": 1e-8,
    "Binance.NEARBUSD.spot": 0.001,
    "Binance.NEARUSDT.spot": 0.001,
    "Binance.AXSBTC.spot": 0.000001,
    "Binance.AXSBUSD.spot": 0.01,
    "Binance.AXSUSDT.spot": 0.01,
    "Binance.FTMBUSD.spot": 0.0001,
    "Binance.FTTBUSD.spot": 0.01,
    "Binance.GALAUSDT.spot": 0.00001,
    "Binance.GALABUSD.spot": 0.00001,
    "Binance.GALABTC.spot": 1e-8,
    "Binance.GMTBTC.spot": 1e-8,
    "Binance.GMTBUSD.spot": 0.00001,
    "Binance.GMTUSDT.spot": 0.00001,
    "Binance.APEUSDT.spot": 0.0001,
    "Binance.APEBUSD.spot": 0.0001,
    "Binance.APEBTC.spot": 1e-8,
    "Binance.GALUSDT.spot": 0.001,
    "Binance.GALBUSD.spot": 0.001,
    "Binance.GALBTC.spot": 1e-8
};

TRANSFER_LIMIT = {
    HuobiSwap: {
        BTC: {in: 0.0001, out: 0.001},
        ETH: {in: 0.01, out: 0.03},
        EOS: {in: 0.1, out: 2},
        XRP: {in: 1, out: 4},
        LTC: {in: 0.01, out: 0.02},
        BSV: {in: 0.01, out: 0.01},
        BCH: {in: 0.01, out: 0.01},
        ETC: {in: 0.1, out: 1},
        TRX: {in: 10, out: 100},
        USDT: {in: 0.45, out: 3.5},
    },
    HuobiFuture: {
        BTC: {in: 0.0001, out: 0.0008},
        ETH: {in: 0.01, out: 0.04},
        EOS: {in: 0.1, out: 2},
        XRP: {in: 1, out: 4},
        LTC: {in: 0.01, out: 0.02},
        BSV: {in: 0.01, out: 0.01},
        BCH: {in: 0.01, out: 0.01},
        ETC: {in: 0.1, out: 1},
        TRX: {in: 10, out: 100},
        USDT: {in: 0.01, out: 0.01},
    }
};

Function.prototype.getName = function () {
    return this.name || this.toString().match(/function\s*([^(]*)\(/)[1]
};

Object.defineProperty(global, '__stack', {
    get: function () {
        let orig = Error.prepareStackTrace;
        Error.prepareStackTrace = function (_, stack) {
            return stack;
        };
        let err = new Error;
        Error.captureStackTrace(err, arguments.callee);
        let stack = err.stack;
        Error.prepareStackTrace = orig;
        return stack;
    }
});

Object.defineProperty(global, '__line', {
    get: function () {
        return __stack[1].getLineNumber();
    }
});

Object.defineProperty(global, '__callee', {
    get: function () {
        return __stack[1].getFunctionName();
    }
});

Object.defineProperty(global, '__caller', {
    get: function () {
        return __stack[2].getFunctionName();
    }
});